[options]
CacheDir = /var/cache/pacman/pkg/ 
HookDir = /home/velle/Documents/GitHub/SYNAPSE/archiso/work/x86_64/airootfs/etc/pacman.d/hooks/
GPGDir = /etc/pacman.d/gnupg/
HoldPkg = pacman
HoldPkg = glibc
Architecture = x86_64
ParallelDownloads = 5
CleanMethod = KeepInstalled
SigLevel = PackageRequired
SigLevel = PackageTrustedOnly
SigLevel = DatabaseOptional
SigLevel = DatabaseTrustedOnly
LocalFileSigLevel = PackageOptional
LocalFileSigLevel = PackageTrustedOnly
[core]
Usage = All
Server = https://geo.mirror.pkgbuild.com/core/os/x86_64
Server = https://mirror.rackspace.com/archlinux/core/os/x86_64
Server = https://mirrors.kernel.org/archlinux/core/os/x86_64
[extra]
Usage = All
Server = https://geo.mirror.pkgbuild.com/extra/os/x86_64
Server = https://mirror.rackspace.com/archlinux/extra/os/x86_64
Server = https://mirrors.kernel.org/archlinux/extra/os/x86_64
[synapseos]
Usage = All
SigLevel = PackageOptional
SigLevel = PackageTrustAll
SigLevel = DatabaseOptional
SigLevel = DatabaseTrustAll
Server = file:///home/velle/Documents/GitHub/SYNAPSE/archiso/local-repo
