[options]
HoldPkg     = pacman glibc
Architecture = auto
ParallelDownloads = 5
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[synapseos]
SigLevel = Optional TrustAll
Server = file:///home/velle/Documents/GitHub/SYNAPSE/archiso/airootfs/local-repo
