#!/usr/bin/env bash
# syn-nix-facts — write /etc/synapseos/nix/facts.nix to stdout
#
# Usage: syn-nix-facts [ROOT]        (ROOT defaults to /)
#
# The bridge between the running SynapseOS and the Nix expressions in
# /etc/synapseos/nix. Nix on a foreign distro cannot see what pacman did, so
# this hands it a description of the machine that home.nix can branch on.
#
# ONE implementation, two callers, and that is the whole point:
#
#   - syn-install runs it with ROOT=/mnt just after the target is populated.
#   - `syn nix facts` runs it with ROOT=/ any time afterwards.
#
# The alternative — the installer writing facts from the ANSWERS it collected,
# and syn re-deriving them later from the system — is two implementations of
# one schema that agree only until someone adds a field to one of them. So
# neither caller passes anything in: this PROBES, always. The installer's
# answers are already visible in what got installed, which has the further
# advantage of staying true afterwards. Install without Steam, add it with
# pacman a month later, run `syn nix facts`, and the facts follow.
#
# Everything is probed by PATH, not by `pacman -Q`: at install time the target
# is a directory, not a running system, and shelling into arch-chroot for
# eight queries is both slower and one more thing to fail.
#
# SynapseOS Project
# SPDX-License-Identifier: GPL-2.0-or-later
set -uo pipefail

ROOT="${1:-/}"
ROOT="${ROOT%/}"          # so "$ROOT/etc" is never "//etc"

# ── Helpers ───────────────────────────────────────────────
# Nix booleans, not shell ones.
have() { [ -e "$ROOT$1" ] && echo true || echo false; }
any()  { local p; for p in "$@"; do [ -e "$ROOT$p" ] && { echo true; return; }; done; echo false; }

# ── Identity ──────────────────────────────────────────────
case "$(uname -m)" in
    x86_64)  SYSTEM="x86_64-linux" ;;
    aarch64) SYSTEM="aarch64-linux" ;;
    *)       SYSTEM="$(uname -m)-linux" ;;
esac

VERSION=$(sed -n 's/^VERSION_ID="\{0,1\}\([^"]*\)"\{0,1\}/\1/p' \
          "$ROOT/etc/os-release" 2>/dev/null | head -1)
VERSION="${VERSION:-unknown}"

HOSTNAME=$(head -1 "$ROOT/etc/hostname" 2>/dev/null)
HOSTNAME="${HOSTNAME:-synapse}"

# The primary human account: lowest uid at or above 1000, skipping nobody.
# nixbld01..10 are system users (sysusers.d only ever creates those), so
# installing Nix first cannot shift this answer.
USERNAME=$(awk -F: '$3 >= 1000 && $3 < 65534 { print $1; exit }' \
           "$ROOT/etc/passwd" 2>/dev/null)
USERNAME="${USERNAME:-syn}"

DESKTOP=$(sed -n 's/^DE=//p' "$ROOT/etc/synapseos/desktop.conf" 2>/dev/null | head -1)
DESKTOP="${DESKTOP:-synui}"

# ── GPU ───────────────────────────────────────────────────
#
# Read from the LIVE host's sysfs in both cases, and correctly so: at install
# time the host and the target are the same machine. $ROOT would be wrong here
# — /mnt/sys is not populated.
#
# Same detection and same precedence as syn-install's video-driver step, so
# the two cannot disagree about what card this is. VM wins outright there
# (synui falls back to pixman), so it wins here.
GPU="none"
if grep -qiE 'VirtualBox|VMware|QEMU|KVM|Xen|innotek' \
        /sys/class/dmi/id/sys_vendor 2>/dev/null; then
    GPU="vm"
else
    for dev in /sys/bus/pci/devices/*; do
        case "$(cat "$dev/class" 2>/dev/null)" in 0x03*) ;; *) continue ;; esac
        case "$(cat "$dev/vendor" 2>/dev/null)" in
            0x10de) GPU="nvidia"; break ;;      # first, like the installer
            0x1002) [ "$GPU" = none ] && GPU="amd" ;;
            0x8086) [ "$GPU" = none ] && GPU="intel" ;;
        esac
    done
fi

# ── Optional groups, as installed ─────────────────────────
W_MODEL=$(have /var/lib/synapd/models/synapse.gguf)
W_BLUETOOTH=$(have /usr/bin/bluetoothctl)
W_PRINTING=$(have /usr/bin/cupsd)
W_FILEMGR=$(any /usr/bin/dolphin /usr/bin/nautilus /usr/bin/thunar)
W_WINE=$(have /usr/bin/wine)
W_PHONE=$(have /usr/bin/kdeconnect-cli)
W_STEAM=$(have /usr/bin/steam)
W_NIX=$(have /usr/bin/nix)

# A repo, not a package — the keyring is what actually lands on disk.
if grep -q '^\[blackarch\]' "$ROOT/etc/pacman.conf" 2>/dev/null; then
    W_BLACKARCH=true
else
    W_BLACKARCH=false
fi

# nvidia's driver and Steam are both unfree. Deciding it here means a fresh
# install evaluates instead of stopping on an allowUnfree error that reads
# like a bug in the flake.
if [ "$GPU" = nvidia ] || [ "$W_STEAM" = true ]; then
    UNFREE=true
else
    UNFREE=false
fi

# ── Emit ──────────────────────────────────────────────────
cat << FACTS
# GENERATED by syn-nix-facts — every edit here is lost on the next run.
#
# Regenerate after changing the machine:  syn nix facts
# Read it from home.nix as \`facts\`;      see /etc/synapseos/nix/home.nix
#
# Probed from ${ROOT:-/} on $(date -u +%Y-%m-%dT%H:%M:%SZ).
{
  system      = "$SYSTEM";
  version     = "$VERSION";
  hostname    = "$HOSTNAME";
  username    = "$USERNAME";
  desktop     = "$DESKTOP";

  # one of: nvidia | amd | intel | vm | none
  gpu         = "$GPU";

  # nvidia and Steam are unfree; the flake passes this to nixpkgs config.
  allowUnfree = $UNFREE;

  want = {
    model     = $W_MODEL;
    bluetooth = $W_BLUETOOTH;
    printing  = $W_PRINTING;
    filemgr   = $W_FILEMGR;
    wine      = $W_WINE;
    phone     = $W_PHONE;
    steam     = $W_STEAM;
    blackarch = $W_BLACKARCH;
    nix       = $W_NIX;
  };
}
FACTS
