pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io

/*
 * Theme.qml — the SYNAPSE bar palette.
 *
 * Colours come from ~/.config/synui/theme.json, which synui-apply-theme writes
 * on every theme switch alongside the waybar CSS. Before that file existed this
 * palette was hardcoded, and the result was a win95 desktop — silver and navy
 * everywhere — with one neon magenta strip across it that no theme switch could
 * move.
 *
 * The bar CANNOT read the generated waybar-style.css instead: QML's colour type
 * parses "#RRGGBB" and SVG names but not CSS rgba(), so every themed colour
 * would silently fall back and the bug would look fixed while doing nothing.
 * Hence a JSON of plain numbers, written atomically by rename.
 *
 * Every colour falls back to the original SYNAPSE palette, so a system that has
 * never applied a theme — a fresh install, or the live ISO — looks exactly as
 * it did before this file learned to read anything.
 */
QtObject {
    id: root

    // Parsed palette, or {} when the file is missing or malformed.
    property var p: ({})

    readonly property bool isLight: p.scheme === "light"

    // QtObject has no default property, so the watcher is held by a named one.
    property FileView paletteFile: FileView {
        path: Quickshell.env("HOME") + "/.config/synui/theme.json"
        watchChanges: true
        // The generator writes a temp file and renames it, so this fires once,
        // with a complete file — never on a half-written palette.
        onFileChanged: reload()
        onLoaded: {
            try {
                root.p = JSON.parse(this.text())
            } catch (e) {
                // A malformed palette must not take the bar down, and must not
                // leave it half-themed either: fall back wholesale.
                root.p = ({})
            }
        }
        onLoadFailed: root.p = ({})
    }

    // ── The UI font ──────────────────────────────────────
    // The bar is part of the desktop, so "set the UI font" has to move it too —
    // a picker that changed every application and left one strip across the top
    // of the screen in the old face would read as broken.
    //
    // Its own file rather than a key in theme.json: that file is regenerated by
    // every theme switch, and the font must OUTLIVE a theme switch. font.state
    // is written by synui-apply-font(1), which is the single writer of every
    // font setting on the box. Empty (or absent) means the shipped default,
    // exactly as it does for the compositor's own panels.
    property string uiFont: ""

    property FileView fontFile: FileView {
        path: Quickshell.env("HOME") + "/.config/synui/font.state"
        watchChanges: true
        // No font.state is the normal case on a box where nobody has picked a
        // font. A WARN per bar start for an expected miss is how a log becomes
        // something nobody reads.
        printErrors: false
        onFileChanged: reload()
        onLoaded: {
            const m = this.text().match(/^\s*family\s*=\s*(.+?)\s*$/m)
            root.uiFont = m ? m[1] : ""
        }
        onLoadFailed: root.uiFont = ""
    }

    // Reading root.p inside these makes every colour below a live binding on
    // it, so a theme switch repaints the bar without a restart.
    function themed(key, r, g, b, a) {
        const c = root.p[key]
        return (c && c.length === 3) ? Qt.rgba(c[0] / 255, c[1] / 255, c[2] / 255, a)
                                     : Qt.rgba(r / 255, g / 255, b / 255, a)
    }
    function pick(dark, light) { return root.isLight ? light : dark }

    // ── A bar with no background of its own ──────────────
    /*
     * macOS 26's menu bar is CLEAR: no strip, no tint, the clock and the menus
     * drawn straight onto the wallpaper. theme.json asks for that with
     * barAlpha 0 (synui-apply-theme, from theme_bar_alpha()) — and so does
     * anyone who drags Control panel ▸ Desktop ▸ Bar opacity down to 0.00, on
     * any theme. See barAlphaAsked below, which is where the two meet.
     *
     * That request is only half an instruction, because a clear bar cannot tint
     * itself into legibility — its ink is on the wallpaper, and the theme's ink
     * is #1D1D1F, which is 12.6:1 on Tahoe's own pale desktop and 1.2:1 on the
     * near-black one this box actually runs. So the compositor measures the
     * strip the bar covers and writes which ink survives it; "none" is a real
     * answer (a mid-tone wallpaper where neither black nor white clears AA, or
     * two monitors that need different answers) and the bar KEEPS ITS
     * BACKGROUND rather than going clear and unreadable.
     */
    property string barInk: ""      // "dark" | "light" | "" (no safe answer)

    /*
     * …and the ink that is merely CLOSEST, for the band where neither is safe.
     *
     * "The bar stops being transparent on some wallpapers, and goes transparent
     * again if I switch" was this, and it was the design working as written: a
     * backdrop between roughly 0.184 and 0.238 relative luminance clears neither
     * ink, so the bar put its whole background back. An evenly-lit photograph
     * lands in that band, the one beside it does not, and from the outside the
     * bar looks like it randomly stops being glass.
     *
     * Falling back to opaque was too big a step. A SCRIM — a thin wash the
     * opposite way from the ink — moves the backdrop clean out of the band and
     * measures around 8:1, at a third of the coverage, so the wallpaper is still
     * plainly visible through the strip. What it needs is a direction, and that
     * is what this value is: see syn_ink_best() in contrast.h.
     */
    property string barInkBest: ""

    // ── The wallpaper's own colours ──────────────────────
    //
    // SYNAPSE Prism takes its accent off the wallpaper (synui's palette.c), and
    // publishes it here on every wallpaper change. Read exactly like
    // backdrop.state next door, and for the same reason: quickshell cannot ask
    // the compositor anything, so a derived fact travels as a file.
    //
    // ⚠ NOT theme.json. That file is written by synui-apply-theme, which is
    // ~20 seconds of kwriteconfig and gsettings — it changes when the THEME
    // does, and this changes when the WALLPAPER does, which on a slideshow is
    // every few minutes.
    //
    // Empty string means "no palette": either the wallpaper had no usable hue
    // (a greyscale photograph), or synui is older than this file. Both are
    // answered the same way — fall through to the theme's own accent — so
    // neither needs telling apart here.
    property string wpAccent: ""
    property string wpAccentDim: ""
    property string wpSecondary: ""

    // ⚠ NOT `paletteFile` — that name is taken, by the theme.json reader at the
    // top of this file. QML answers a duplicate property with "Type Theme
    // unavailable" three imports up the chain, so the bar does not load AT ALL
    // and the error names shell.qml rather than this line. qmllint does not
    // catch it; the bar_opacity rig, which actually starts the shell, does.
    property FileView wpPaletteFile: FileView {
        path: Quickshell.env("HOME") + "/.config/synui/palette.state"
        watchChanges: true
        printErrors: false          // absent until a wallpaper has been measured
        onFileChanged: reload()
        onLoaded: {
            const t = this.text()
            const ok = /^\s*ok\s*=\s*yes\s*$/m.test(t)
            function hex(key) {
                const m = t.match(new RegExp("^\\s*" + key + "\\s*=\\s*(#[0-9A-Fa-f]{6})\\s*$", "m"))
                return (ok && m) ? m[1] : ""
            }
            root.wpAccent    = hex("accent")
            root.wpAccentDim = hex("accent_dim")
            root.wpSecondary = hex("secondary")
        }
        onLoadFailed: { root.wpAccent = ""; root.wpAccentDim = ""; root.wpSecondary = "" }
    }

    property FileView backdropFile: FileView {
        path: Quickshell.env("HOME") + "/.config/synui/backdrop.state"
        watchChanges: true
        printErrors: false          // absent until a wallpaper has been painted
        onFileChanged: reload()
        onLoaded: {
            const t = this.text()
            const m = t.match(/^\s*bar_ink\s*=\s*(\S+)\s*$/m)
            const v = m ? m[1] : "none"
            root.barInk = (v === "dark" || v === "light") ? v : ""
            // Absent from a backdrop.state written by an older synui, which
            // leaves barInkUsed equal to barInk and every behaviour below
            // exactly what it was before the scrim existed.
            const b = t.match(/^\s*bar_ink_best\s*=\s*(\S+)\s*$/m)
            const bv = b ? b[1] : "none"
            root.barInkBest = (bv === "dark" || bv === "light") ? bv : ""
        }
        onLoadFailed: { root.barInk = ""; root.barInkBest = "" }
    }

    // The ink actually drawn: the safe one where there is one, the closest one
    // otherwise. Empty only when the backdrop could not be measured at all — a
    // video wallpaper, or two monitors that want opposite answers — and THAT is
    // still a bar that keeps its background, because there is no one answer to
    // draw for both screens.
    readonly property string barInkUsed: root.barInk !== "" ? root.barInk
                                                            : root.barInkBest

    /*
     * How opaque the bar is ASKED to be, before the wallpaper gets a say.
     *
     * Two sources and one of them wins outright: the user's row (Control panel ▸
     * Desktop ▸ Bar opacity, out of settings.state via BarConfig) over the
     * theme's own barAlpha from theme.json. Negative from BarConfig is not a
     * number — it is "nobody has chosen", which is its default and leaves the
     * theme's answer standing exactly as it did before the row existed.
     *
     * -1 is the no-answer value on BOTH sides here, which is what lets this be
     * one property rather than a pair of undefined-checks: theme.json omits
     * barAlpha on every preset but macOS 26, and a bar reading a theme.json
     * written by an older synui must land on the same "no answer" as a fresh
     * install. Falling through to bgAlphaDefault is where that is resolved.
     */
    readonly property real barAlphaAsked:
        BarConfig.barOpacity >= 0 ? BarConfig.barOpacity
      : (p.barAlpha !== undefined ? p.barAlpha : -1)

    // The bar is clear only when it is ASKED to be AND an ink survives the
    // wallpaper. Either half alone is a bar you cannot read.
    readonly property bool clearBar: root.barAlphaAsked === 0 && root.barInkUsed !== ""

    // …and it is clear-WITH-A-SCRIM when the ink it is using is the closest one
    // rather than a safe one. Nothing else changes: same ink, same modules, one
    // wash behind them.
    readonly property bool barScrim: root.clearBar && root.barInk === ""

    // How strong that wash is. 0.34 is what it takes to move the worst case in
    // the band (backdrop ≈ 0.20) to roughly 8:1 — comfortably past AA, with the
    // wallpaper still reading through it. Below about 0.25 the worst case does
    // not clear; much above 0.4 and it stops looking like glass and starts
    // looking like the opaque strip this replaced.
    readonly property real scrimAlpha: 0.34

    // Which way the ink runs. On a clear bar that is the backdrop's answer, not
    // the scheme's — a light theme over a dark wallpaper wants WHITE text, which
    // is the whole point.
    readonly property bool inkOnDark: root.clearBar ? (root.barInkUsed === "light")
                                                    : !root.isLight

    // ── Surfaces ─────────────────────────────────────────
    // The scheme's default, and also the floor a clear bar falls back to when
    // the wallpaper offers no legible ink. Spelt once so the two cannot drift.
    readonly property real  bgAlphaDefault: root.isLight ? 0.95 : 0.85
    readonly property real  bgAlpha:    root.barScrim ? root.scrimAlpha
                                      : root.clearBar ? 0.0
                                      : root.barAlphaAsked > 0
                                        ? root.barAlphaAsked : root.bgAlphaDefault
    readonly property real  popupAlpha: p.popupAlpha !== undefined ? p.popupAlpha : 0.97

    // The scrim is BLACK or WHITE and not the theme's bar colour, which is the
    // one place this diverges from `bg` meaning "the theme's surface at some
    // alpha". Its whole job is to move the backdrop away from the ink, and the
    // theme's bar colour is chosen to sit UNDER that ink — Tahoe's is near-white
    // and so is the wash it would lay under white text. So it follows the ink,
    // not the palette: light ink darkens the backdrop, dark ink lightens it.
    readonly property color bg: root.barScrim
        ? (root.inkOnDark ? Qt.rgba(0, 0, 0, root.scrimAlpha)
                          : Qt.rgba(1, 1, 1, root.scrimAlpha))
        : themed("bar", 11, 11, 20, bgAlpha)
    readonly property color bgSolid: themed("bar",   11, 11, 20, 1.0)
    readonly property color popupBg: themed("popup", 11, 11, 20, popupAlpha)

    // The washes track the colours they tint, so a hover on a Gruvbox bar is
    // Gruvbox rather than the old cyan.
    //
    // The wallpaper's accent wins where there is one — that IS Prism, and on
    // every other theme the file is absent or says no and these fall straight
    // through to themed() unchanged.
    readonly property color hoverBg:  root.wpAccentDim !== ""
        ? Qt.rgba(Qt.color(root.wpAccentDim).r, Qt.color(root.wpAccentDim).g,
                  Qt.color(root.wpAccentDim).b, 0.15)
        : themed("glyph",   5, 217, 232, 0.15)
    readonly property color activeBg: root.wpAccent !== ""
        ? Qt.rgba(Qt.color(root.wpAccent).r, Qt.color(root.wpAccent).g,
                  Qt.color(root.wpAccent).b, 0.20)
        : themed("accent", 255,  41, 109, 0.20)

    // ── Ink ──────────────────────────────────────────────
    readonly property color fg:      p.fg      ? Qt.color(p.fg)      : "#c8e3ee"
    readonly property color cyan:    themed("glyph",   5, 217, 232, 1.0)   // module glyphs
    readonly property color magenta: root.wpAccent !== ""
        ? Qt.color(root.wpAccent)
        : themed("accent", 255,  41, 109, 1.0)  // accent + underline
    readonly property color yellow:  p.clockFg ? Qt.color(p.clockFg) : "#ffd319"

    // Not themed, because these carry MEANING rather than style: green is
    // charging, red is a battery about to die. They only switch on light/dark,
    // where the pastels are unreadable on a pale bar — the same reason
    // synui-apply-theme darkens the clock's yellow for light schemes.
    readonly property color fgDim:  pick("#3a4a52", "#6b7280")
    readonly property color blue:   pick("#4dabff", "#1d4ed8")
    readonly property color green:  pick("#a6e3a1", "#166534")
    readonly property color red:    pick("#f38ba8", "#b91c1c")
    readonly property color orange: pick("#f9e2af", "#8a6d00")

    // ── …and the STRIP's, which is a different surface ───
    /*
     * Everything above is drawn on a surface this palette owns: the strip when
     * it has a background, and every popup, menu and widget that opens off it.
     * A CLEAR strip is the one thing that is not — it is drawn on the wallpaper,
     * and the wallpaper is not something the theme knows.
     *
     * So the strip gets its own set of names, and `modules/*` and BarModule use
     * THOSE. Not the pair above renamed: the bar's right-click menu, the start
     * menu, the mixer and the widgets keep drawing on popupBg, which is solid
     * and pale on a light theme, and flipping their ink to white to suit the
     * wallpaper behind the strip would black-on-black exactly the surfaces this
     * change never touches.
     *
     * When the strip is not clear every one of these IS its counterpart above,
     * which is what makes this inert for the twelve themes that do not ask.
     */
    function barPick(dark, light) { return root.inkOnDark ? dark : light }

    // The one colour a clear strip is allowed. Tahoe's menu bar is monochrome
    // for exactly this reason: over an unknown backdrop the palette's blues and
    // yellows are a contrast nothing can vouch for — this theme's #0056D6 glyph
    // measures 3.2:1 on a near-black wallpaper. Black and white are the two that
    // can be, which is what syn_ink_for_backdrop() chooses between.
    readonly property color barInkColor: root.inkOnDark ? "#ffffff" : "#1d1d1f"

    readonly property color barFg:     root.clearBar ? root.barInkColor : root.fg
    readonly property color barGlyph:  root.clearBar ? root.barInkColor : root.cyan
    readonly property color barAccent: root.clearBar ? root.barInkColor : root.magenta
    readonly property color barClock:  root.clearBar ? root.barInkColor : root.yellow

    // A 15% accent wash over a photograph is not a hover state, it is nothing.
    // On a clear strip the wash is the ink, at the strength it takes to read as
    // a button against whatever is behind it.
    readonly property color barHoverBg:  root.clearBar
        ? Qt.rgba(root.barInkColor.r, root.barInkColor.g, root.barInkColor.b, 0.18)
        : root.hoverBg
    readonly property color barActiveBg: root.clearBar
        ? Qt.rgba(root.barInkColor.r, root.barInkColor.g, root.barInkColor.b, 0.28)
        : root.activeBg

    // The status colours keep their MEANING on a clear strip — a red battery
    // warning turned white is a warning nobody reads — and only swap which half
    // of each pair suits the backdrop.
    readonly property color barDim:    barPick("#3a4a52", "#6b7280")
    readonly property color barBlue:   barPick("#4dabff", "#1d4ed8")
    readonly property color barGreen:  barPick("#a6e3a1", "#166534")
    readonly property color barRed:    barPick("#f38ba8", "#b91c1c")
    readonly property color barOrange: barPick("#f9e2af", "#8a6d00")

    // ── Metrics ──────────────────────────────────────────
    // 28px matches the waybar height the compositor already lays out around:
    // synui's launcher (launcher.c) draws "◢ SYNAPSE" over the bar's top-left
    // corner, and its geometry assumes this height.
    readonly property int  barHeight:     28
    readonly property int  accentHeight:  2      // the accent underline
    readonly property int  modulePadH:    9
    readonly property int  moduleGap:     2

    // The CONTROLS: menu rows, workspace pills, tray cells, the mixer's little
    // adjust chips. Everything that lives INSIDE a panel and is 18-22px tall.
    // Deliberately not the desktop's radius — these are 4px because at that
    // height anything more is a lozenge, and `corner_radius = 14` would turn a
    // row highlight into a capsule while saying nothing about what the user
    // asked for, which was rounded panels.
    readonly property int  radius:        4

    /*
     * The SURFACES: the right-click menu, the start menu, the mixer, the module
     * tooltips, the OSD. These are furniture on the same desktop as synui's own
     * panels, so they take the same setting the compositor draws its control
     * panel and its pickers with — see panel_chrome_sync() in render.c, which is
     * the other half of this. Before it, "rounded corners" moved every window
     * and every application on the desktop and left the desktop's own furniture
     * square.
     *
     * TWO sources because the fact has two halves with different lifetimes. The
     * radius is a setting the user can change at any moment (BarConfig reads it
     * from the three files synui reads it from, in synui's order). Whether the
     * chrome overrides it to square is a property of the THEME, changing only
     * when the theme does — so it rides in theme.state, written by theme.c,
     * which is the one place that knows a Win95 desktop is square whatever the
     * slider says. Deriving that here would mean a copy of the LUNA/BEVEL table
     * in QML, wrong the first time a preset changes.
     */
    readonly property int  panelRadius:   root.squareChrome ? 0
                                                            : BarConfig.cornerRadius

    /*
     * ── The bar's own shape ──────────────────────────────────
     *
     * panelRadius is what the bar's POPUPS use. This is the strip itself, and it
     * is a separate question because a bar is not a popup: it spans the monitor
     * and sits against an edge, so "rounded" has to say which corners and
     * whether it still touches that edge. BarConfig.barShape answers both.
     *
     * ALL OF IT IS GATED ON panelRadius > 0, which is the whole contract of the
     * setting (see syn_bar_shape_t): the shape is what to do WHEN the corners
     * are on, not a second switch. So a desktop with the slider at zero, and
     * every retro chrome, keeps the square edge-to-edge strip whatever this row
     * says — and nothing here needs to know what LUNA or BEVEL are, because
     * squareChrome already folded that in above.
     *
     * Unknown values behave as full-width: `pill` and `ends` are positive tests,
     * so a settings.state from a newer synui degrades to the shape that has
     * always worked rather than to a shape this bar cannot draw.
     */
    readonly property bool barRounded: root.panelRadius > 0
    readonly property bool barPill:    root.barRounded
                                       && BarConfig.barShape === "floating-pill"
    readonly property bool barEnds:    root.barRounded
                                       && BarConfig.barShape === "rounded-ends"

    /*
     * How far the pill floats: off the edge it lives on, and in from both sides.
     * One number for both so the gap reads as even all the way round.
     *
     * It is deliberately NOT the corner radius. The radius is a curve on a shape
     * and this is the space around it — tying them together would mean a desktop
     * at radius 2 got a 2px gap (a pill that looks like a rendering mistake) and
     * one at 48 got a 48px gap (a bar floating in the middle of the screen).
     */
    readonly property int  barGap:     root.barPill ? 6 : 0

    /*
     * The capsule radius. Half the height is what makes the ends semicircular —
     * the definition of the shape, not a taste — so it follows barHeight rather
     * than the user's radius, which is about corners and not about being round.
     *
     * `ends` takes the desktop's radius instead: that bar still spans the
     * monitor, and a capsule end on a shape 1900px wide is not a pill, it is a
     * racetrack. Its TOP pair stays square in Bar.qml — the corners at the
     * screen edge have nothing to round against.
     */
    readonly property int  barRadius:  root.barPill ? Math.round(root.barHeight / 2)
                                     : root.barEnds ? root.panelRadius
                                                    : 0

    /* Total height the bar's WINDOW needs, which is the strip plus the gap it
     * floats by. The exclusive zone is this, not barHeight: a pill that reserved
     * only its own height would have maximized windows slide under the gap and
     * up against its underside. */
    readonly property int  barSpan:    root.barHeight + root.barGap

    // Absent, unreadable, or written by a synui too old to export it: not
    // square. That is the modern chrome, which is what all but two of the
    // presets are, and it degrades to exactly the behaviour above.
    property bool squareChrome: false

    /* ── Glass ───────────────────────────────────────────────
     *
     * The other half of the same file, and the same kind of fact: does this
     * desktop's chrome do FROSTED GLASS — translucent surfaces over a blurred
     * backdrop — rather than a tinted slab? theme.c exports it because nothing
     * over here can work it out: theme.json carries a palette and a scheme, and
     * "light" is XP and Win95 as much as it is Tahoe.
     *
     * `widgetGlass` is the user's override on top, out of settings.state, in
     * synui's own precedence (settings.state, then synuirc). "auto" is the
     * default and means the theme decides — the same three positions the dock's
     * own `dock_style` row has, and deliberately spelt the same way.
     */
    property bool squareChromeGlass: false

    // What the desktop widgets actually do. The one property WidgetFrame reads.
    readonly property bool widgetsGlass:
        BarConfig.widgetGlass === "on"  ? true :
        BarConfig.widgetGlass === "off" ? false : root.squareChromeGlass

    /*
     * …and how transparent they are when they do. The ASK was that the widgets
     * match the dock, so this is the dock's own opacity rather than a second
     * number that starts equal to it and drifts the first time either is
     * touched. config.c's default is 0.72 and it clamps to 0.20-1.00; BarConfig
     * re-does that clamp for the same reason it re-does corner_radius's.
     *
     * Not applied verbatim, though, and the difference is the point: the dock
     * is a bar of icons with a real blur behind it, and a widget is a card of
     * SMALL TEXT on whatever the wallpaper happens to be. Quickshell's layer
     * surfaces get no backdrop blur here — that is a compositor node the dock
     * has and these do not — so the same alpha over an unblurred photograph is a
     * sysmon readout nobody can read. The lift is what buys the text a surface
     * while still tracking the slider.
     */
    readonly property real widgetAlpha: Math.min(1.0, BarConfig.dockOpacity + 0.16)

    property FileView chromeFile: FileView {
        path: Quickshell.env("HOME") + "/.config/synui/theme.state"
        watchChanges: true
        // Synchronous for the same reason BarConfig's uifxFile is: squareChrome
        // is the other half of "are the corners on", so it too decides whether a
        // floating pill reserves its gap, and the exclusive zone cannot learn
        // that a frame later. A retro desktop read asynchronously would come up
        // holding a gap it does not draw.
        blockLoading: true
        printErrors: false      // absent until a theme is picked
        onFileChanged: reload()
        onLoaded: {
            const t = this.text()
            const m = t.match(/^\s*square_chrome\s*=\s*(\S+)\s*$/m)
            root.squareChrome = !!m && m[1] === "on"
            // Absent means a synui too old to export it, which is a desktop
            // whose widgets have always been the HUD panel. Off is the honest
            // answer for both that and a theme that really is not glass.
            const g = t.match(/^\s*glass_chrome\s*=\s*(\S+)\s*$/m)
            root.squareChromeGlass = !!g && g[1] === "on"
        }
        onLoadFailed: {
            root.squareChrome = false
            root.squareChromeGlass = false
        }
    }

    // Module pills are inset from the bar's height so the hover wash reads as a
    // button rather than a full-height stripe. 20 of 28 leaves 4px above and
    // below; the radius is half the height, which is what makes it a pill and
    // not a rounded box.
    readonly property int  pillHeight:    20
    readonly property int  pillRadius:    10

    // Auto-hide: the strip left taking pointer input while the bar is hidden,
    // and how long it waits before dropping once nothing wants it up. The strip
    // has to be thicker than a hairline on a monitor whose top edge is not the
    // layout's top edge — there the pointer arrives from the screen above at
    // whatever step the motion event carries instead of being clamped to y=0,
    // so a 1-2px target gets jumped clean over. The delay is what stops a
    // pointer merely crossing the edge from flapping the bar down and back up.
    readonly property int  barEdgeStrip:  5
    readonly property int  barHideDelay:  260

    // Follows the picker; DejaVu Sans Mono is the floor, and what a box that
    // has never picked one keeps looking like.
    readonly property string fontFamily:  root.uiFont !== "" ? root.uiFont
                                                             : "DejaVu Sans Mono"
    // NOT the picked font, ever. These are the Nerd Font's Private-Use
    // codepoints, and no ordinary family has a glyph at U+F026 — pointing this
    // at "Adwaita Sans" turns every module's icon into a tofu box and collapses
    // the icon-only modules (bluetooth) to zero width.
    readonly property string iconFamily:  "Symbols Nerd Font Mono"
    readonly property int    fontSize:    12
    readonly property int    iconSize:    13

    // Shared easing so every module animates identically.
    readonly property int  animFast:   120
    readonly property int  animNormal: 180
}
