pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io

/*
 * Theme.qml — the SYNAPSE bar palette.
 *
 * Colours come from ~/.config/synui/theme.json, which synui-apply-theme writes
 * on every theme switch alongside the waybar CSS. Before that file existed this
 * palette was hardcoded, and the result was a win95 desktop — silver and navy
 * everywhere — with one neon magenta strip across it that no theme switch could
 * move.
 *
 * The bar CANNOT read the generated waybar-style.css instead: QML's colour type
 * parses "#RRGGBB" and SVG names but not CSS rgba(), so every themed colour
 * would silently fall back and the bug would look fixed while doing nothing.
 * Hence a JSON of plain numbers, written atomically by rename.
 *
 * Every colour falls back to the original SYNAPSE palette, so a system that has
 * never applied a theme — a fresh install, or the live ISO — looks exactly as
 * it did before this file learned to read anything.
 */
QtObject {
    id: root

    // Parsed palette, or {} when the file is missing or malformed.
    property var p: ({})

    readonly property bool isLight: p.scheme === "light"

    // QtObject has no default property, so the watcher is held by a named one.
    property FileView paletteFile: FileView {
        path: Quickshell.env("HOME") + "/.config/synui/theme.json"
        watchChanges: true
        // The generator writes a temp file and renames it, so this fires once,
        // with a complete file — never on a half-written palette.
        onFileChanged: reload()
        onLoaded: {
            try {
                root.p = JSON.parse(this.text())
            } catch (e) {
                // A malformed palette must not take the bar down, and must not
                // leave it half-themed either: fall back wholesale.
                root.p = ({})
            }
        }
        onLoadFailed: root.p = ({})
    }

    // ── The UI font ──────────────────────────────────────
    // The bar is part of the desktop, so "set the UI font" has to move it too —
    // a picker that changed every application and left one strip across the top
    // of the screen in the old face would read as broken.
    //
    // Its own file rather than a key in theme.json: that file is regenerated by
    // every theme switch, and the font must OUTLIVE a theme switch. font.state
    // is written by synui-apply-font(1), which is the single writer of every
    // font setting on the box. Empty (or absent) means the shipped default,
    // exactly as it does for the compositor's own panels.
    property string uiFont: ""

    property FileView fontFile: FileView {
        path: Quickshell.env("HOME") + "/.config/synui/font.state"
        watchChanges: true
        // No font.state is the normal case on a box where nobody has picked a
        // font. A WARN per bar start for an expected miss is how a log becomes
        // something nobody reads.
        printErrors: false
        onFileChanged: reload()
        onLoaded: {
            const m = this.text().match(/^\s*family\s*=\s*(.+?)\s*$/m)
            root.uiFont = m ? m[1] : ""
        }
        onLoadFailed: root.uiFont = ""
    }

    // Reading root.p inside these makes every colour below a live binding on
    // it, so a theme switch repaints the bar without a restart.
    function themed(key, r, g, b, a) {
        const c = root.p[key]
        return (c && c.length === 3) ? Qt.rgba(c[0] / 255, c[1] / 255, c[2] / 255, a)
                                     : Qt.rgba(r / 255, g / 255, b / 255, a)
    }
    function pick(dark, light) { return root.isLight ? light : dark }

    // ── A bar with no background of its own ──────────────
    /*
     * macOS 26's menu bar is CLEAR: no strip, no tint, the clock and the menus
     * drawn straight onto the wallpaper. theme.json asks for that with
     * barAlpha 0 (synui-apply-theme, from theme_bar_alpha()) — and so does
     * anyone who drags Control panel ▸ Desktop ▸ Bar opacity down to 0.00, on
     * any theme. See barAlphaAsked below, which is where the two meet.
     *
     * That request is only half an instruction, because a clear bar cannot tint
     * itself into legibility — its ink is on the wallpaper, and the theme's ink
     * is #1D1D1F, which is 12.6:1 on Tahoe's own pale desktop and 1.2:1 on the
     * near-black one this box actually runs. So the compositor measures the
     * strip the bar covers and writes which ink survives it; "none" is a real
     * answer (a mid-tone wallpaper where neither black nor white clears AA, or
     * two monitors that need different answers) and the bar KEEPS ITS
     * BACKGROUND rather than going clear and unreadable.
     */
    property string barInk: ""      // "dark" | "light" | "" (no safe answer)

    /*
     * …and the ink that is merely CLOSEST, for the band where neither is safe.
     *
     * "The bar stops being transparent on some wallpapers, and goes transparent
     * again if I switch" was this, and it was the design working as written: a
     * backdrop between roughly 0.184 and 0.238 relative luminance clears neither
     * ink, so the bar put its whole background back. An evenly-lit photograph
     * lands in that band, the one beside it does not, and from the outside the
     * bar looks like it randomly stops being glass.
     *
     * Falling back to opaque was too big a step. A SCRIM — a thin wash the
     * opposite way from the ink — moves the backdrop clean out of the band and
     * measures around 8:1, at a third of the coverage, so the wallpaper is still
     * plainly visible through the strip. What it needs is a direction, and that
     * is what this value is: see syn_ink_best() in contrast.h.
     */
    property string barInkBest: ""

    /*
     * ── …and both of them asked of ONE SCREEN ────────────────
     *
     * ⚠ THERE IS ONE BAR PER OUTPUT, SO THE PAIR ABOVE IS ONE ANSWER FOR ALL OF
     * THEM, AND THAT IS THE BUG THIS EXISTS TO FIX.
     *
     * backdrop_export() folds the monitors with syn_ink_combine, which vetoes on
     * disagreement — the right answer for ONE surface lying across two screens,
     * and the wrong one for the bar, which is a separate layer surface on each
     * output with its own strip of its own wallpaper underneath it.
     *
     * What that cost, measured on a three-monitor desk: two 1440p desktops whose
     * top strip was 0.67 wanted dark ink, and a television showing the same
     * wallpaper letterboxed — so its top row of cells is the black band — wanted
     * light. The fold said "none", `barInkUsed` went empty, `clearBar` went
     * false, and macOS 26 and Prism, the two presets whose entire look is a bar
     * that is not there, put an opaque strip back on ALL THREE SCREENS. One
     * black band on one television turned the glass off for the desktop.
     *
     * Keyed by connector name. Empty for a bar reading a backdrop.state written
     * before these lines existed, which is what barInkOn() falls back for.
     */
    property var barInks: ({})       // output name → "dark" | "light" | anything else
    property var barInkBests: ({})

    // ── The wallpaper's own colours ──────────────────────
    //
    // SYNAPSE Prism takes its accent off the wallpaper (synui's palette.c), and
    // publishes it here on every wallpaper change. Read exactly like
    // backdrop.state next door, and for the same reason: quickshell cannot ask
    // the compositor anything, so a derived fact travels as a file.
    //
    // ⚠ NOT theme.json. That file is written by synui-apply-theme, which is
    // ~20 seconds of kwriteconfig and gsettings — it changes when the THEME
    // does, and this changes when the WALLPAPER does, which on a slideshow is
    // every few minutes.
    //
    // Empty string means "no palette": either the wallpaper had no usable hue
    // (a greyscale photograph), or synui is older than this file. Both are
    // answered the same way — fall through to the theme's own accent — so
    // neither needs telling apart here.
    property string wpAccent: ""
    property string wpAccentDim: ""
    property string wpSecondary: ""

    // ⚠ NOT `paletteFile` — that name is taken, by the theme.json reader at the
    // top of this file. QML answers a duplicate property with "Type Theme
    // unavailable" three imports up the chain, so the bar does not load AT ALL
    // and the error names shell.qml rather than this line. qmllint does not
    // catch it; the bar_opacity rig, which actually starts the shell, does.
    property FileView wpPaletteFile: FileView {
        path: Quickshell.env("HOME") + "/.config/synui/palette.state"
        watchChanges: true
        printErrors: false          // absent until a wallpaper has been measured
        onFileChanged: reload()
        onLoaded: {
            const t = this.text()
            const ok = /^\s*ok\s*=\s*yes\s*$/m.test(t)
            function hex(key) {
                const m = t.match(new RegExp("^\\s*" + key + "\\s*=\\s*(#[0-9A-Fa-f]{6})\\s*$", "m"))
                return (ok && m) ? m[1] : ""
            }
            root.wpAccent    = hex("accent")
            root.wpAccentDim = hex("accent_dim")
            root.wpSecondary = hex("secondary")
        }
        onLoadFailed: { root.wpAccent = ""; root.wpAccentDim = ""; root.wpSecondary = "" }
    }

    property FileView backdropFile: FileView {
        path: Quickshell.env("HOME") + "/.config/synui/backdrop.state"
        watchChanges: true
        printErrors: false          // absent until a wallpaper has been painted
        onFileChanged: reload()
        onLoaded: {
            const t = this.text()
            const m = t.match(/^\s*bar_ink\s*=\s*(\S+)\s*$/m)
            const v = m ? m[1] : "none"
            root.barInk = (v === "dark" || v === "light") ? v : ""
            // Absent from a backdrop.state written by an older synui, which
            // leaves barInkUsed equal to barInk and every behaviour below
            // exactly what it was before the scrim existed.
            const b = t.match(/^\s*bar_ink_best\s*=\s*(\S+)\s*$/m)
            const bv = b ? b[1] : "none"
            root.barInkBest = (bv === "dark" || bv === "light") ? bv : ""

            // …and the same two answers asked of ONE screen. Absent from a
            // backdrop.state written by an older synui, and barInkOn() falls
            // back to the folded pair above when a name is missing — so a bar
            // on that synui behaves exactly as it did before these existed.
            const inks = {}, bests = {}
            const ire = /^\s*bar_ink(_best)?\.(\S+)\s*=\s*(\S+)\s*$/gm
            let im
            while ((im = ire.exec(t)) !== null)
                (im[1] ? bests : inks)[im[2]] = im[3]
            root.barInks = inks
            root.barInkBests = bests

            // The per-output luminance grids, for every surface that is not the
            // bar. Absent from a backdrop.state written by an older synui, and
            // an empty map is exactly the "nothing measured" that inkFor()
            // already has to answer for a video wallpaper — so the upgrade path
            // is the one that was already there.
            const g = {}
            const re = /^\s*grid\.(\S+)\s*=\s*([-0-9.,]+)\s*$/gm
            let mm
            while ((mm = re.exec(t)) !== null) {
                const cells = mm[2].split(",").map(parseFloat)
                if (cells.length === root.lumCols * root.lumRows) g[mm[1]] = cells
            }
            root.lumGrids = g

            // …and the same grid measured off what is ACTUALLY on screen
            // (barscan.c), which is the wallpaper only until a window covers
            // it. -1 here means "nothing covers this cell", NOT "unmeasurable"
            // — backdropFor() takes lumGrids' matching cell for those. Absent
            // from an older synui's backdrop.state, and from any desktop with
            // `scene_ink` off; an empty map means every cell falls back, which
            // is precisely the behaviour that predates this.
            const sg = {}
            const sre = /^\s*scene\.(\S+)\s*=\s*([-0-9.,]+)\s*$/gm
            let sm
            while ((sm = sre.exec(t)) !== null) {
                const cells = sm[2].split(",").map(parseFloat)
                if (cells.length === root.lumCols * root.lumRows) sg[sm[1]] = cells
            }
            root.sceneGrids = sg

            // And the one row that is NOT the wallpaper: what is actually under
            // the bar, column by column (barscan.c). A column of -1 is one that
            // nothing covers, which is the ordinary case — barStripAt() takes
            // the wallpaper's own top-row cell for those. Absent from an older
            // synui's backdrop.state, and an empty map means every column falls
            // back, which is precisely the behaviour that predates this.
            const bs = {}
            const bre = /^\s*bar_strip\.(\S+)\s*=\s*([-0-9.,]+)\s*$/gm
            let bm
            while ((bm = bre.exec(t)) !== null) {
                const cols = bm[2].split(",").map(parseFloat)
                if (cols.length === root.lumCols) bs[bm[1]] = cols
            }
            root.barStrips = bs
        }
        onLoadFailed: {
            root.barInk = ""; root.barInkBest = ""; root.lumGrids = ({})
            root.barInks = ({}); root.barInkBests = ({}); root.barStrips = ({})
            root.sceneGrids = ({})
        }
    }

    /*
     * ── Which ink reads on the wallpaper under THIS surface ──
     *
     * The bar's two questions, asked for a box instead of for the top strip.
     * Everything the shell draws that is not the bar — the start menu, the bar's
     * own menus, the mixer, the widgets, the OSD — opens where it is put, so
     * "which ink is legible" stopped being one answer per desktop the moment
     * they went see-through too.
     *
     * ⚠ THE GRID IS THE COMPOSITOR'S, NOT A SECOND MEASUREMENT. synui measures
     * the wallpaper it painted and publishes the cells; this only folds the ones
     * a box covers. The alternative — the shell sampling the screen itself —
     * would be a second answer that could disagree with the one the compositor's
     * own panels are using, and the whole point is that a menu and the control
     * panel beside it are the same amount of glass in the same direction.
     */
    readonly property int lumCols: 16
    readonly property int lumRows: 9
    property var lumGrids: ({})

    /*
     * output name → the same grid, measured off the SCENE (barscan.c).
     *
     * ⚠ THE WALLPAPER IS NOT WHAT IS BEHIND A MENU, and for a whole release's
     * worth of surfaces it was the only thing any of them could ask about. The
     * bar got the answer first because the bar was the first surface a window
     * could get behind — but the start menu, the bar's own menus, the mixer and
     * the OSD open WHERE THEY ARE PUT, and on a desktop with anything running
     * that is over a window far more often than over the picture. A menu opened
     * over a dark browser was choosing its ink from the pale photograph the
     * browser covers, which is the same bug with a bigger surface on it.
     *
     * ⚠ -1 MEANS "NOTHING COVERS THIS CELL", exactly as it does in barStrips
     * and NOT as it does in lumGrids. There the value means the wallpaper could
     * not be measured and the surface must keep its background; here it means
     * the wallpaper IS the backdrop and its cell is the correct answer rather
     * than a second-best guess. backdropFor() resolves the two per cell, which
     * is the only place they meet.
     */
    property var sceneGrids: ({})

    /*
     * output name → lumCols luminances across the BAR STRIP, from barscan.c.
     *
     * The wallpaper is not always what is behind the bar. It is whenever the bar
     * reserves its exclusive zone, which is the default and is why this did not
     * exist for a long time — but an auto-hiding bar reserves nothing and every
     * maximized window comes up underneath it, and a floating window can be
     * dragged over the strip on any bar at all. In both, the strip of wallpaper
     * wp_top_lum measured is not on screen, and the bar inks itself for a
     * picture the user cannot see.
     *
     * ⚠ -1 IS "NOTHING COVERS THIS COLUMN", NOT "UNMEASURABLE", and the two
     * want opposite handling: unmeasurable means keep your background, uncovered
     * means the wallpaper's answer is the right one after all. barStripAt()
     * resolves it per column, which is the only place the two grids meet.
     */
    property var barStrips: ({})

    // Contrast of a fixed ink against a backdrop luminance, WCAG. The ink
    // luminances are the same two constants contrast.h names, so the C side and
    // this agree on where the band is rather than each rounding it its own way.
    readonly property real inkDarkLum:  0.0122771   // #1D1D1F
    readonly property real inkLightLum: 1.0         // #FFFFFF
    function lumContrast(a, b) {
        const hi = Math.max(a, b), lo = Math.min(a, b)
        return (hi + 0.05) / (lo + 0.05)
    }

    /*
     * Fold the cells a box covers into { lum, ink, best } — the same three
     * things syn_backdrop_for_box() returns on the C side, in the same order of
     * preference. `ink` is "clear is safe here", `best` is "clear is safe once
     * you have dimmed it this way", and `ink` empty with a real `best` is a
     * scrim. Disagreeing cells veto, exactly as two monitors do for the bar: one
     * surface draws one colour of text, and a menu lying half on sky and half on
     * shadow has no single colour that reads on both.
     *
     * Screen coordinates in, so callers pass what they already have. A surface
     * on a screen synui has not measured gets lum -1 and no ink, which every
     * caller has to read as "keep the background you had".
     */
    function backdropFor(screen, x, y, w, h) {
        const none = { lum: -1, ink: "", best: "" }
        if (!screen) return none
        const cells = root.lumGrids[screen.name]
        if (!cells || screen.width <= 0 || screen.height <= 0) return none
        // The scene's answer where it has one, per CELL. Absent for a desktop
        // with `scene_ink` off, or a synui too old to publish it, and then
        // every cell falls through to the wallpaper below — which is what this
        // function did before the scene grid existed.
        const scene = root.sceneGrids[screen.name]

        const c0 = Math.max(0, Math.min(root.lumCols - 1,
                            Math.floor(x / screen.width  * root.lumCols)))
        const r0 = Math.max(0, Math.min(root.lumRows - 1,
                            Math.floor(y / screen.height * root.lumRows)))
        const c1 = Math.max(c0, Math.min(root.lumCols - 1,
                            Math.floor((x + w) / screen.width  * root.lumCols)))
        const r1 = Math.max(r0, Math.min(root.lumRows - 1,
                            Math.floor((y + h) / screen.height * root.lumRows)))

        let sum = 0, n = 0, ink = null, best = null
        for (let r = r0; r <= r1; r++) {
            for (let c = c0; c <= c1; c++) {
                const i = r * root.lumCols + c
                const s = scene ? scene[i] : -1
                const l = s >= 0 ? s : cells[i]
                if (!(l >= 0)) return none      // one unmeasured cell vetoes
                sum += l; n++
                const cd = root.lumContrast(root.inkDarkLum,  l)
                const cl = root.lumContrast(root.inkLightLum, l)
                // 4.5 is CONTRAST_TARGET; neither passing is a real answer and
                // the important one — that is the band the scrim exists for.
                const one  = (cd < 4.5 && cl < 4.5) ? "" : (cd >= cl ? "dark" : "light")
                const bst  = cd >= cl ? "dark" : "light"
                ink  = ink  === null ? one : (ink  === one ? ink  : "")
                best = best === null ? bst : (best === bst ? best : "")
            }
        }
        if (!n) return none
        return { lum: sum / n, ink: ink || "", best: best || "" }
    }

    // The ink actually drawn: the safe one where there is one, the closest one
    // otherwise. Empty only when the backdrop could not be measured at all — a
    // video wallpaper, or two monitors that want opposite answers — and THAT is
    // still a bar that keeps its background, because there is no one answer to
    // draw for both screens.
    readonly property string barInkUsed: root.barInk !== "" ? root.barInk
                                                            : root.barInkBest

    /*
     * How opaque the bar is ASKED to be, before the wallpaper gets a say.
     *
     * Two sources and one of them wins outright: the user's row (Control panel ▸
     * Desktop ▸ Bar opacity, out of settings.state via BarConfig) over the
     * theme's own barAlpha from theme.json. Negative from BarConfig is not a
     * number — it is "nobody has chosen", which is its default and leaves the
     * theme's answer standing exactly as it did before the row existed.
     *
     * -1 is the no-answer value on BOTH sides here, which is what lets this be
     * one property rather than a pair of undefined-checks: theme.json omits
     * barAlpha on every preset but macOS 26, and a bar reading a theme.json
     * written by an older synui must land on the same "no answer" as a fresh
     * install. Falling through to bgAlphaDefault is where that is resolved.
     */
    readonly property real barAlphaAsked:
        BarConfig.barOpacity >= 0 ? BarConfig.barOpacity
      : (p.barAlpha !== undefined ? p.barAlpha : -1)

    // The bar is clear only when it is ASKED to be AND an ink survives the
    // wallpaper. Either half alone is a bar you cannot read.
    readonly property bool clearBar: root.barAlphaAsked === 0 && root.barInkUsed !== ""

    // …and it is clear-WITH-A-SCRIM when the ink it is using is the closest one
    // rather than a safe one. Nothing else changes: same ink, same modules, one
    // wash behind them.
    readonly property bool barScrim: root.clearBar && root.barInk === ""

    // How strong that wash is. 0.34 is what it takes to move the worst case in
    // the band (backdrop ≈ 0.20) to roughly 8:1 — comfortably past AA, with the
    // wallpaper still reading through it. Below about 0.25 the worst case does
    // not clear; much above 0.4 and it stops looking like glass and starts
    // looking like the opaque strip this replaced.
    readonly property real scrimAlpha: 0.34

    // Which way the ink runs. On a clear bar that is the backdrop's answer, not
    // the scheme's — a light theme over a dark wallpaper wants WHITE text, which
    // is the whole point.
    readonly property bool inkOnDark: root.clearBar ? (root.barInkUsed === "light")
                                                    : !root.isLight

    // ── Surfaces ─────────────────────────────────────────
    // The scheme's default, and also the floor a clear bar falls back to when
    // the wallpaper offers no legible ink. Spelt once so the two cannot drift.
    readonly property real  bgAlphaDefault: root.isLight ? 0.95 : 0.85
    readonly property real  bgAlpha:    root.barScrim ? root.scrimAlpha
                                      : root.clearBar ? 0.0
                                      : root.barAlphaAsked > 0
                                        ? root.barAlphaAsked : root.bgAlphaDefault
    /*
     * The start menu, the bar's menu, the mixer, the widgets and the OSD.
     *
     * 0.97 is "solid, with the barest hint that something is behind it", which
     * is right for the twelve themes that are not glass and wrong for the ones
     * that are: on a glass theme every one of these opened as a slab in front of
     * windows that were themselves frosted. synui frosts what is behind them now
     * (layer.c keys off the `synui-glass` namespace) — and a blur behind an
     * opaque surface is invisible, so this is the half that makes it show.
     *
     * ⚠ NOT as low as the compositor's own panels go. These carry dense rows of
     * small text over an UNKNOWN backdrop, and unlike synui's panels they have
     * no ink ladder that re-measures itself against the surface — the numbers in
     * this file were chosen against popupBg as it stands. 0.86 is where the
     * wallpaper reads through clearly and a 10px menu row still holds together;
     * the theme's own popupAlpha, where it states one, still wins outright.
     */
    readonly property real  popupAlphaGlass: 0.86

    /*
     * ⚠ theme.json's popupAlpha IS NOT A THEME'S OPINION, and reading it as one
     * is why none of the above ever ran.
     *
     * The line looked like the barAlpha resolution three properties up — "the
     * theme states one, so the theme wins" — but the two keys are not the same
     * kind of thing. synui-apply-theme.sh writes barAlpha only where a preset
     * has an answer, and writes popupAlpha ALWAYS: it is `menu_alpha`, a
     * constant of the SCHEME (0.97 dark, 0.99 light) that no preset can
     * override, emitted into every theme.json on the way past. So the key was
     * always present, the test always passed, and `popupAlphaGlass` was
     * unreachable on every desktop that has ever run — the start menu opened as
     * a 0.97 slab in front of frosted windows no matter what the theme was.
     *
     * So the resolution goes to the desktop's own number instead, and to the
     * SAME number the bar uses. That is the whole of "the menus match the bar":
     * barAlphaAsked is bar_opacity where the user has set one and the theme's
     * barAlpha otherwise, and the C side resolves exactly that field for
     * synui's own panels (syn_glass_resolve). One number, one desktop.
     *
     * ⚠ AND IT IS NOT FLOORED HERE. The old 0.86 was a guess at "as low as a
     * menu can go anywhere", and it is replaced by asking: backdropFor() says
     * which ink reads on the wallpaper under this particular surface, and the
     * scrim covers the band where neither does. A menu can follow the bar all
     * the way down because it now has the same machinery the bar had.
     *
     * The scheme constant is still the fallback for a desktop that has set no
     * opacity and whose theme is not glass — the twelve retro presets, which
     * should look exactly as they always did.
     */
    readonly property real  popupAlpha:
        root.barAlphaAsked >= 0   ? root.barAlphaAsked
      : root.glassSurfaces        ? root.popupAlphaGlass
      : (p.popupAlpha !== undefined ? p.popupAlpha : 0.97)

    // The scrim is BLACK or WHITE and not the theme's bar colour, which is the
    // one place this diverges from `bg` meaning "the theme's surface at some
    // alpha". Its whole job is to move the backdrop away from the ink, and the
    // theme's bar colour is chosen to sit UNDER that ink — Tahoe's is near-white
    // and so is the wash it would lay under white text. So it follows the ink,
    // not the palette: light ink darkens the backdrop, dark ink lightens it.
    readonly property color bg: root.barScrim
        ? (root.inkOnDark ? Qt.rgba(0, 0, 0, root.scrimAlpha)
                          : Qt.rgba(1, 1, 1, root.scrimAlpha))
        : themed("bar", 11, 11, 20, bgAlpha)
    readonly property color bgSolid: themed("bar",   11, 11, 20, 1.0)
    readonly property color popupBg: themed("popup", 11, 11, 20, popupAlpha)

    /*
     * ── A popup that knows what it is sitting on ─────────────
     *
     * popupBg above is the surface at the alpha the desktop ASKED for, which is
     * all a solid menu ever needed. Once the menus follow the bar down they need
     * the other half of what the bar has: the bar can be drawn at 0.00 only
     * because backdrop.state tells it which ink survives there, and a menu that
     * took the same number without the same knowledge would just be an
     * unreadable menu.
     *
     * Two moves, in this order, and the order is the point:
     *
     *   1. RAISE THE ALPHA until the theme's own ink reads on the composite.
     *      Preferred because it keeps the theme's colours — the menu is still
     *      recognisably Gruvbox, or Prism, just less see-through in the one spot
     *      where the wallpaper was fighting it.
     *   2. Only if that runs out, FLIP THE INK to the black or white the
     *      backdrop actually carries. That is the bar's answer, and it is the
     *      last resort here because a menu has more to lose by abandoning its
     *      palette than a bar with six glyphs on it does.
     *
     * A surface over an unmeasured wallpaper keeps exactly what it asked for:
     * -1 means synui cannot see what is back there, and guessing would put the
     * slab back on one wallpaper source and nowhere else.
     */

    // Relative luminance of a QML colour, WCAG. Same curve as contrast.c's
    // syn_rel_luminance — the two sides decide the same things about the same
    // pixels and must not each round the transfer function their own way.
    function lumOf(c) {
        function lin(v) { return v <= 0.03928 ? v / 12.92
                                              : Math.pow((v + 0.055) / 1.055, 2.4) }
        return 0.2126 * lin(c.r) + 0.7152 * lin(c.g) + 0.0722 * lin(c.b)
    }

    // A surface of luminance `s` at `a` over a backdrop of luminance `b`.
    // Mixed in the ENCODING the GPU mixes in, for the reason syn_lum_over()
    // spells out: a linear mix of luminances is several hundredths out in the
    // midtones, which is the whole width of the band the ink flips in.
    function lumOver(s, a, b) {
        if (!(b >= 0)) return s
        if (a >= 1) return s
        if (a <= 0) return b
        function enc(v) { return v <= 0.0031308 ? v * 12.92
                                                : 1.055 * Math.pow(v, 1 / 2.4) - 0.055 }
        function lin(v) { return v <= 0.03928 ? v / 12.92
                                              : Math.pow((v + 0.055) / 1.055, 2.4) }
        return lin(a * enc(s) + (1 - a) * enc(b))
    }

    // The alpha this popup actually has to draw at, given what is behind it.
    // The QML twin of render.c's panel_alpha_floor(), asking the same question
    // of the same wallpaper: walk up from what was asked until full-strength
    // text clears AA on the composite.
    function popupAlphaOn(bd) {
        // ⚠ The correction is a setting, and off means off — the same switch
        // render.c's panel_alpha_floor() answers to. Half the desktop obeying it
        // would be worse than neither half doing.
        if (!BarConfig.legibility) return root.popupAlpha
        if (!bd || !(bd.lum >= 0)) return root.popupAlpha
        const surf = root.lumOf(root.popupBg)
        const ink  = root.lumOf(root.fg)
        for (let a = root.popupAlpha; a < 1.0; a += 0.02)
            if (root.lumContrast(ink, root.lumOver(surf, a, bd.lum)) >= 4.5) return a
        return 1.0
    }

    /*
     * …and the ink to draw on it: the theme's own wherever it still reads on
     * what this popup is about to present, the backdrop's black-or-white where
     * it does not.
     *
     * ⚠ THE TEST IS THE CONTRAST AT THE ALPHA ACTUALLY DRAWN, and it used to be
     * `popupAlphaOn(bd) < 1.0` — "the walk found an alpha, so the theme's ink is
     * safe". That reads as a shorthand for this and is one, right up until the
     * walk does not run: popupAlphaOn returns the asked-for alpha untouched when
     * `glass_legibility` is off, which is never 1.0, so the shorthand answered
     * "safe" for every backdrop on earth and the flip was unreachable.
     *
     * That is not a corner. A macOS 26 or Prism desktop asks barAlpha 0, so
     * popupAlpha is 0 — the start menu has NO surface of its own, exactly like
     * the clear bar — and with the correction off it drew the theme's dark ink
     * straight onto whatever was there. Over a dark window that is a menu of
     * invisible text, and the bar sitting above it was choosing black or white
     * per module the whole time (barPaletteAt).
     *
     * ⚠ AND THE FLIP IS NOT GATED ON glass_legibility, deliberately. That switch
     * means "do not make my glass opaque" — it governs the ALPHA. Choosing which
     * of two inks to draw at the alpha the user asked for takes nothing away
     * from them, and it is precisely what clearBarOn() already does for the bar
     * with the correction off. A menu that stays as see-through as it was asked
     * to be and becomes readable is the whole point of the setting.
     *
     * With the correction ON nothing here moves: popupAlphaOn has already walked
     * the alpha up until this same contrast passes, so the test passes and the
     * theme keeps its colours — and where the walk ran out at 1.0 the test fails
     * and the ink flips, which is what the old shorthand did.
     */
    function popupFgOn(bd) {
        if (!bd || !(bd.lum >= 0)) return root.fg
        const a    = root.popupAlphaOn(bd)
        const surf = root.lumOf(root.popupBg)
        const ink  = root.lumOf(root.fg)
        if (root.lumContrast(ink, root.lumOver(surf, a, bd.lum)) >= 4.5)
            return root.fg
        const which = bd.ink !== "" ? bd.ink : bd.best
        if (which === "") return root.fg
        return which === "light" ? "#ffffff" : "#1d1d1f"
    }

    /*
     * The DIM ink for the same surface — placeholder text, a menu row that is
     * off, the second line of a pair.
     *
     * fgDim is a fixed pair of greys chosen against popupBg, so on a popup whose
     * ink has flipped it is the one label left in the palette the flip just
     * abandoned: a #6b7280 "Type to search" on a menu drawing white on a dark
     * window. It follows the flip instead, at the same 65% the greys already sit
     * at relative to the ink they accompany, so a row that is off still reads as
     * off rather than as a row that is missing.
     */
    function popupFgDimOn(bd) {
        const fg = root.popupFgOn(bd)
        if (Qt.colorEqual(fg, root.fg)) return root.fgDim
        // ⚠ Qt.color() and not `fg` directly: popupFgOn hands back a STRING in
        // the flipped case and a colour in the other, which a property binding
        // coerces for free and `.r` on a JS string does not — it is undefined,
        // and Qt.rgba(undefined…) is a silent black.
        const c = Qt.color(fg)
        return Qt.rgba(c.r, c.g, c.b, 0.65)
    }

    // The surface itself at that alpha. What a popup binds its background to.
    function popupBgOn(bd) {
        return themed("popup", 11, 11, 20, root.popupAlphaOn(bd))
    }

    // The washes track the colours they tint, so a hover on a Gruvbox bar is
    // Gruvbox rather than the old cyan.
    //
    // The wallpaper's accent wins where there is one — that IS Prism, and on
    // every other theme the file is absent or says no and these fall straight
    // through to themed() unchanged.
    readonly property color hoverBg:  root.wpAccentDim !== ""
        ? Qt.rgba(Qt.color(root.wpAccentDim).r, Qt.color(root.wpAccentDim).g,
                  Qt.color(root.wpAccentDim).b, 0.15)
        : themed("glyph",   5, 217, 232, 0.15)
    readonly property color activeBg: root.wpAccent !== ""
        ? Qt.rgba(Qt.color(root.wpAccent).r, Qt.color(root.wpAccent).g,
                  Qt.color(root.wpAccent).b, 0.20)
        : themed("accent", 255,  41, 109, 0.20)

    // ── Ink ──────────────────────────────────────────────
    readonly property color fg:      p.fg      ? Qt.color(p.fg)      : "#c8e3ee"
    readonly property color cyan:    themed("glyph",   5, 217, 232, 1.0)   // module glyphs
    readonly property color magenta: root.wpAccent !== ""
        ? Qt.color(root.wpAccent)
        : themed("accent", 255,  41, 109, 1.0)  // accent + underline
    readonly property color yellow:  p.clockFg ? Qt.color(p.clockFg) : "#ffd319"

    // Not themed, because these carry MEANING rather than style: green is
    // charging, red is a battery about to die. They only switch on light/dark,
    // where the pastels are unreadable on a pale bar — the same reason
    // synui-apply-theme darkens the clock's yellow for light schemes.
    readonly property color fgDim:  pick("#3a4a52", "#6b7280")
    readonly property color blue:   pick("#4dabff", "#1d4ed8")
    readonly property color green:  pick("#a6e3a1", "#166534")
    readonly property color red:    pick("#f38ba8", "#b91c1c")
    readonly property color orange: pick("#f9e2af", "#8a6d00")

    // ── …and the STRIP's, which is a different surface ───
    /*
     * Everything above is drawn on a surface this palette owns: the strip when
     * it has a background, and every popup, menu and widget that opens off it.
     * A CLEAR strip is the one thing that is not — it is drawn on the wallpaper,
     * and the wallpaper is not something the theme knows.
     *
     * So the strip gets its own set of names, and `modules/*` and BarModule use
     * THOSE. Not the pair above renamed: the bar's right-click menu, the start
     * menu, the mixer and the widgets keep drawing on popupBg, which is solid
     * and pale on a light theme, and flipping their ink to white to suit the
     * wallpaper behind the strip would black-on-black exactly the surfaces this
     * change never touches.
     *
     * When the strip is not clear every one of these IS its counterpart above,
     * which is what makes this inert for the twelve themes that do not ask.
     */
    function barPick(dark, light) { return root.inkOnDark ? dark : light }

    // The one colour a clear strip is allowed. Tahoe's menu bar is monochrome
    // for exactly this reason: over an unknown backdrop the palette's blues and
    // yellows are a contrast nothing can vouch for — this theme's #0056D6 glyph
    // measures 3.2:1 on a near-black wallpaper. Black and white are the two that
    // can be, which is what syn_ink_for_backdrop() chooses between.
    readonly property color barInkColor: root.inkOnDark ? "#ffffff" : "#1d1d1f"

    readonly property color barFg:     root.clearBar ? root.barInkColor : root.fg
    readonly property color barGlyph:  root.clearBar ? root.barInkColor : root.cyan
    readonly property color barAccent: root.clearBar ? root.barInkColor : root.magenta
    readonly property color barClock:  root.clearBar ? root.barInkColor : root.yellow

    // A 15% accent wash over a photograph is not a hover state, it is nothing.
    // On a clear strip the wash is the ink, at the strength it takes to read as
    // a button against whatever is behind it.
    readonly property color barHoverBg:  root.clearBar
        ? Qt.rgba(root.barInkColor.r, root.barInkColor.g, root.barInkColor.b, 0.18)
        : root.hoverBg
    readonly property color barActiveBg: root.clearBar
        ? Qt.rgba(root.barInkColor.r, root.barInkColor.g, root.barInkColor.b, 0.28)
        : root.activeBg

    // The status colours keep their MEANING on a clear strip — a red battery
    // warning turned white is a warning nobody reads — and only swap which half
    // of each pair suits the backdrop.
    readonly property color barDim:    barPick("#3a4a52", "#6b7280")
    readonly property color barBlue:   barPick("#4dabff", "#1d4ed8")
    readonly property color barGreen:  barPick("#a6e3a1", "#166534")
    readonly property color barRed:    barPick("#f38ba8", "#b91c1c")
    readonly property color barOrange: barPick("#f9e2af", "#8a6d00")

    /* ── The same strip palette, for ONE screen ──────────────
     *
     * Everything above is the folded answer, and it stays: it is what a surface
     * with no screen to name still gets, and on a single-monitor desktop it and
     * the per-output answer are the same two values.
     *
     * These are what Bar.qml and BarModule read. The bar is per-output and its
     * backdrop is per-output, so its ink has to be too — see `barInks`.
     */
    function inkNamed(v) { return (v === "dark" || v === "light") ? v : "" }

    function barInkOn(name) {
        return (name && root.barInks[name] !== undefined)
             ? root.inkNamed(root.barInks[name]) : root.barInk
    }
    function barInkBestOn(name) {
        return (name && root.barInkBests[name] !== undefined)
             ? root.inkNamed(root.barInkBests[name]) : root.barInkBest
    }
    function barInkUsedOn(name) {
        const i = root.barInkOn(name)
        return i !== "" ? i : root.barInkBestOn(name)
    }

    /*
     * The two halves of "is this screen's bar clear", exactly as clearBar and
     * barScrim ask them of the desktop as a whole.
     *
     * ⚠ WITH THE LEGIBILITY CORRECTION OFF, ASKING IS ENOUGH. "No ink survives
     * this wallpaper, so keep your background" is a correction like any other —
     * the most visible one on the desktop, in fact, since it is the difference
     * between a clear bar and an opaque strip — and the switch that turns the
     * others off has to turn this off too or it would be a switch that does
     * everything except the thing people notice. The scrim goes with it: it is
     * the same correction, applied more gently.
     */
    function clearBarOn(name) {
        if (root.barAlphaAsked !== 0) return false
        return !BarConfig.legibility || root.barInkUsedOn(name) !== ""
    }
    function barScrimOn(name) {
        return BarConfig.legibility && root.clearBarOn(name)
                                    && root.barInkOn(name) === ""
    }

    /*
     * One object with everything a bar on `screen` draws with.
     *
     * A function returning an object rather than a dozen `barFgOn(name)`
     * properties, because every one of them turns on the SAME two booleans: a
     * caller that resolved `clear` for the fg and again for the hover wash is a
     * caller that can get the two out of step. Bound as
     * `readonly property var pal: Theme.barPalette(screen)`, so it re-evaluates
     * when the screen changes and when backdrop.state does — the bindings track
     * the properties this reads, the same way popupAlphaOn() is tracked.
     *
     * A null screen is a real case (a module whose window has not been assigned
     * one yet) and answers with the folded desktop-wide values, which is what
     * every one of these was before this existed.
     */
    /*
     * The same thing, taking the WINDOW a module is in rather than its screen.
     *
     * `QsWindow.window` is typed as a bare QObject, so dotting `.screen` off it
     * at each of the fifteen call sites is fifteen qmllint warnings for one fact
     * qmllint cannot know. One untyped hop, here, and the callers pass what they
     * actually have.
     */
    function barPaletteOf(win) { return root.barPalette(win ? win.screen : null) }

    /*
     * ── The bar, asked one SECTION at a time ─────────────────
     *
     * Everything above answers for a whole bar, because for a whole bar's worth
     * of releases the backdrop was the wallpaper strip and the wallpaper strip
     * was one number. Once a WINDOW can be under the bar, the strip stops being
     * uniform at the window's edge: the workspace pills sit on wallpaper and the
     * clock sits on a dark browser, and one ink for the pair is wrong at one end
     * or the other. That edge is a hard boundary in the middle of a surface,
     * which is exactly what the per-output fix was NOT — that one moved a veto
     * off a boundary that was never inside a single surface.
     *
     * `x`/`w` are in the BAR WINDOW's coordinates, which is what a module has:
     * the bar spans its output, so they are the output's own coordinates offset
     * by nothing. A module passes its own geometry and gets the palette for the
     * strip it personally covers.
     */

    /* The luminances under [x, x+w) on this screen's bar, one per column the
     * span touches, with the wallpaper answering for every column no window
     * covers. Empty when this screen has been measured for neither. */
    function barStripAt(screen, x, w) {
        const out = []
        if (!screen || screen.width <= 0) return out

        const strip = root.barStrips[screen.name]
        const grid  = root.lumGrids[screen.name]
        if (!strip && !grid) return out

        const c0 = Math.max(0, Math.min(root.lumCols - 1,
                            Math.floor(x / screen.width * root.lumCols)))
        const c1 = Math.max(c0, Math.min(root.lumCols - 1,
                            Math.ceil((x + w) / screen.width * root.lumCols) - 1))

        for (let c = c0; c <= c1; c++) {
            // The scene's answer first, and ONLY where it has one. This is the
            // whole fallback: -1 from barscan is a column with nothing over the
            // wallpaper, so the wallpaper's top row is not a second-best guess
            // there, it is the correct measurement.
            const s = strip ? strip[c] : -1
            if (s >= 0) { out.push(s); continue }
            // Row 0 of the grid is the top of the output. A bottom bar wants the
            // LAST row, for the same reason wallpaper.c measures the strip on
            // the edge the bar is actually on.
            const row = BarConfig.atBottom ? root.lumRows - 1 : 0
            const g = grid ? grid[row * root.lumCols + c] : -1
            out.push(g >= 0 ? g : -1)
        }
        return out
    }

    /*
     * The palette for one section of the bar: barPalette's answer, re-decided
     * against what is under THIS span.
     *
     * Falls all the way back to barPalette(screen) whenever the span has no
     * measurement of its own, so a module that asks about a screen synui has not
     * measured — or one on a build with no barscan — gets exactly what it got
     * before this function existed.
     *
     * ⚠ THE VETO STILL APPLIES WITHIN A SPAN, and it has to: syn_ink_combine's
     * rule is that one surface draws one colour of text, and a single module
     * lying half on a dark window and half on pale wallpaper genuinely has no
     * colour that reads on both. Such a module takes the scrim, which is the
     * same answer the whole bar used to take for the same reason — only now it
     * is one module wearing it instead of all of them.
     */
    function barPaletteAt(screen, x, w) {
        const base = root.barPalette(screen)
        if (!base.clear) return base        // an opaque bar has no backdrop problem

        const cells = root.barStripAt(screen, x, w)
        if (cells.length === 0) return base

        let ink = null, best = null
        for (let i = 0; i < cells.length; i++) {
            const l = cells[i]
            if (!(l >= 0)) return base      // one unmeasured column and the span
                                            // has no better answer than the bar's
            const cd = root.lumContrast(root.inkDarkLum,  l)
            const cl = root.lumContrast(root.inkLightLum, l)
            const one = (cd < 4.5 && cl < 4.5) ? "" : (cd >= cl ? "dark" : "light")
            const bst = cd >= cl ? "dark" : "light"
            ink  = ink  === null ? one : (ink  === one ? ink  : "")
            best = best === null ? bst : (best === bst ? best : "")
        }
        ink = ink || ""; best = best || ""

        /*
         * ⚠ A SECTION MAY CHANGE THE INK'S DIRECTION BUT NEVER WHETHER THERE IS
         * A SCRIM, and that is a deliberate limit rather than an oversight.
         *
         * The scrim is drawn by ONE rectangle spanning the whole bar (Bar.qml's
         * `color: bar.pal.bg`), so "this third of the bar is scrimmed" is not a
         * thing the bar can currently express. Rather than half-express it —
         * hand a module the `best` ink and let it draw over a backdrop nobody
         * dimmed, which is the unreadable case the scrim exists to prevent —
         * a span with no SAFE ink defers to the bar's own answer entirely.
         *
         * The one exception is where the bar has already laid its scrim: the
         * dimming is on screen over this span too, so following the span's own
         * `best` under it is strictly better than following the whole bar's.
         */
        if (ink !== "")
            return root.barPaletteInked(base, ink === "light", false)
        if (base.scrim && best !== "")
            return root.barPaletteInked(base, best === "light", true)
        return base
    }

    /*
     * The form a bar MODULE calls: its window, itself, and its own geometry.
     *
     * ⚠ `x` AND `w` ARE PASSED RATHER THAN READ OFF `item`, and the reason is
     * that this is called from a binding. mapToItem() is a function call the QML
     * engine cannot see into, so a binding that only called it would never
     * re-run — a module would keep the ink for wherever it happened to be when
     * the bar was first laid out, and the media module, which resizes with every
     * track, would be wrong most of the time. Naming them in the caller's
     * argument list is what puts them in the binding's dependency set.
     *
     * The lookup itself still needs mapToItem: a module knows its x within the
     * Row it sits in, and the strip is indexed in the bar window's coordinates.
     *
     * The untyped `win.screen` hop stays HERE, in Theme.qml, for the same reason
     * barPaletteOf() exists — QsWindow.window is a bare QObject, and dotting
     * .screen off it at every call site is a qmllint warning per site.
     */
    function barPaletteSpan(win, item, x, w) {
        if (!win || !item) return root.barPalette(win ? win.screen : null)
        const p = item.mapToItem(null, 0, 0)
        return root.barPaletteAt(win.screen, p.x, w > 0 ? w : item.width)
    }

    /* barPaletteAt() and barPalette() differ only in HOW they arrive at the two
     * booleans — which way the ink runs, and whether it needs a scrim under it.
     * Spelt once so the fifteen colours below cannot drift between the two. */
    function barPaletteInked(base, dark, scrim) {
        if (dark === base.inkOnDark && scrim === base.scrim) return base
        const ink  = dark ? "#ffffff" : "#1d1d1f"
        const wash = Qt.color(ink)
        function pk(d, l) { return dark ? d : l }
        return {
            clear:     base.clear,
            scrim:     scrim,
            inkOnDark: dark,
            ink:       ink,
            bg:        scrim ? (dark ? Qt.rgba(0, 0, 0, root.scrimAlpha)
                                     : Qt.rgba(1, 1, 1, root.scrimAlpha))
                             : Qt.rgba(0, 0, 0, 0),
            fg:        ink,
            glyph:     ink,
            accent:    ink,
            clock:     ink,
            hoverBg:   Qt.rgba(wash.r, wash.g, wash.b, 0.18),
            activeBg:  Qt.rgba(wash.r, wash.g, wash.b, 0.28),
            dim:       pk("#3a4a52", "#6b7280"),
            blue:      pk("#4dabff", "#1d4ed8"),
            green:     pk("#a6e3a1", "#166534"),
            red:       pk("#f38ba8", "#b91c1c"),
            orange:    pk("#f9e2af", "#8a6d00"),
        }
    }

    function barPalette(screen) {
        const n     = screen ? screen.name : ""
        const clear = root.clearBarOn(n)
        const used  = root.barInkUsedOn(n)
        // A clear bar with a measured ink takes it; one drawn clear ANYWAY —
        // the correction switched off over an unmeasurable wallpaper — has
        // nothing to take, and falls back to the scheme's own direction. That
        // is a guess, and it is the only honest one available: it is what the
        // theme's designer chose for the surface this strip replaced.
        const dark  = (clear && used !== "") ? (used === "light") : !root.isLight
        const ink   = dark ? "#ffffff" : "#1d1d1f"
        const wash  = Qt.color(ink)
        function pk(d, l) { return dark ? d : l }
        return {
            clear:    clear,
            scrim:    root.barScrimOn(n),
            inkOnDark: dark,
            ink:      ink,
            bg:       root.barScrimOn(n)
                        ? (dark ? Qt.rgba(0, 0, 0, root.scrimAlpha)
                                : Qt.rgba(1, 1, 1, root.scrimAlpha))
                      : clear ? Qt.rgba(0, 0, 0, 0)
                      /* Asked for clear and refused it — no legible ink on this
                       * screen — falls to the scheme's own alpha, which is the
                       * same rung `bgAlpha` lands a refused bar on. */
                      : root.themed("bar", 11, 11, 20,
                                    root.barAlphaAsked > 0 ? root.barAlphaAsked
                                                           : root.bgAlphaDefault),
            fg:       clear ? ink : root.fg,
            glyph:    clear ? ink : root.cyan,
            accent:   clear ? ink : root.magenta,
            clock:    clear ? ink : root.yellow,
            hoverBg:  clear ? Qt.rgba(wash.r, wash.g, wash.b, 0.18) : root.hoverBg,
            activeBg: clear ? Qt.rgba(wash.r, wash.g, wash.b, 0.28) : root.activeBg,
            dim:      pk("#3a4a52", "#6b7280"),
            blue:     pk("#4dabff", "#1d4ed8"),
            green:    pk("#a6e3a1", "#166534"),
            red:      pk("#f38ba8", "#b91c1c"),
            orange:   pk("#f9e2af", "#8a6d00"),
        }
    }

    // ── Metrics ──────────────────────────────────────────
    // 28px matches the waybar height the compositor already lays out around:
    // synui's launcher (launcher.c) draws "◢ SYNAPSE" over the bar's top-left
    // corner, and its geometry assumes this height.
    readonly property int  barHeight:     28
    readonly property int  accentHeight:  2      // the accent underline
    readonly property int  modulePadH:    9
    readonly property int  moduleGap:     2

    // The CONTROLS: menu rows, workspace pills, tray cells, the mixer's little
    // adjust chips. Everything that lives INSIDE a panel and is 18-22px tall.
    // Deliberately not the desktop's radius — these are 4px because at that
    // height anything more is a lozenge, and `corner_radius = 14` would turn a
    // row highlight into a capsule while saying nothing about what the user
    // asked for, which was rounded panels.
    readonly property int  radius:        4

    /*
     * The SURFACES: the right-click menu, the start menu, the mixer, the module
     * tooltips, the OSD. These are furniture on the same desktop as synui's own
     * panels, so they take the same setting the compositor draws its control
     * panel and its pickers with — see panel_chrome_sync() in render.c, which is
     * the other half of this. Before it, "rounded corners" moved every window
     * and every application on the desktop and left the desktop's own furniture
     * square.
     *
     * TWO sources because the fact has two halves with different lifetimes. The
     * radius is a setting the user can change at any moment (BarConfig reads it
     * from the three files synui reads it from, in synui's order). Whether the
     * chrome overrides it to square is a property of the THEME, changing only
     * when the theme does — so it rides in theme.state, written by theme.c,
     * which is the one place that knows a Win95 desktop is square whatever the
     * slider says. Deriving that here would mean a copy of the LUNA/BEVEL table
     * in QML, wrong the first time a preset changes.
     */
    readonly property int  panelRadius:   root.squareChrome ? 0
                                                            : BarConfig.cornerRadius

    /*
     * ── The bar's own shape ──────────────────────────────────
     *
     * panelRadius is what the bar's POPUPS use. This is the strip itself, and it
     * is a separate question because a bar is not a popup: it spans the monitor
     * and sits against an edge, so "rounded" has to say which corners and
     * whether it still touches that edge. BarConfig.barShape answers both.
     *
     * ALL OF IT IS GATED ON panelRadius > 0, which is the whole contract of the
     * setting (see syn_bar_shape_t): the shape is what to do WHEN the corners
     * are on, not a second switch. So a desktop with the slider at zero, and
     * every retro chrome, keeps the square edge-to-edge strip whatever this row
     * says — and nothing here needs to know what LUNA or BEVEL are, because
     * squareChrome already folded that in above.
     *
     * Unknown values behave as full-width: `pill` and `ends` are positive tests,
     * so a settings.state from a newer synui degrades to the shape that has
     * always worked rather than to a shape this bar cannot draw.
     */
    readonly property bool barRounded: root.panelRadius > 0
    readonly property bool barPill:    root.barRounded
                                       && BarConfig.barShape === "floating-pill"
    readonly property bool barEnds:    root.barRounded
                                       && BarConfig.barShape === "rounded-ends"

    /*
     * How far the pill floats: off the edge it lives on, and in from both sides.
     * One number for both so the gap reads as even all the way round.
     *
     * It is deliberately NOT the corner radius. The radius is a curve on a shape
     * and this is the space around it — tying them together would mean a desktop
     * at radius 2 got a 2px gap (a pill that looks like a rendering mistake) and
     * one at 48 got a 48px gap (a bar floating in the middle of the screen).
     */
    readonly property int  barGap:     root.barPill ? 6 : 0

    /*
     * The capsule radius. Half the height is what makes the ends semicircular —
     * the definition of the shape, not a taste — so it follows barHeight rather
     * than the user's radius, which is about corners and not about being round.
     *
     * `ends` takes the desktop's radius instead: that bar still spans the
     * monitor, and a capsule end on a shape 1900px wide is not a pill, it is a
     * racetrack. Its TOP pair stays square in Bar.qml — the corners at the
     * screen edge have nothing to round against.
     */
    readonly property int  barRadius:  root.barPill ? Math.round(root.barHeight / 2)
                                     : root.barEnds ? root.panelRadius
                                                    : 0

    /* Total height the bar's WINDOW needs, which is the strip plus the gap it
     * floats by. The exclusive zone is this, not barHeight: a pill that reserved
     * only its own height would have maximized windows slide under the gap and
     * up against its underside. */
    readonly property int  barSpan:    root.barHeight + root.barGap

    // Absent, unreadable, or written by a synui too old to export it: not
    // square. That is the modern chrome, which is what all but two of the
    // presets are, and it degrades to exactly the behaviour above.
    property bool squareChrome: false

    /* ── Glass ───────────────────────────────────────────────
     *
     * The other half of the same file, and the same kind of fact: does this
     * desktop's chrome do FROSTED GLASS — translucent surfaces over a blurred
     * backdrop — rather than a tinted slab? theme.c exports it because nothing
     * over here can work it out: theme.json carries a palette and a scheme, and
     * "light" is XP and Win95 as much as it is Tahoe.
     *
     * `widgetGlass` is the user's override on top, out of settings.state, in
     * synui's own precedence (settings.state, then synuirc). "auto" is the
     * default and means the theme decides — the same three positions the dock's
     * own `dock_style` row has, and deliberately spelt the same way.
     */
    property bool squareChromeGlass: false

    /*
     * …and whether that glass is actually being DRAWN, which is a different
     * question with a different answer.
     *
     * squareChromeGlass is the PRESET's intent. This is the resolved fact —
     * preset AND transparency AND blur — and it is the one popupAlpha keys off,
     * because a popup made see-through on a desktop with blur switched off is a
     * menu with a sharp wallpaper behind it rather than glass. synui exports it
     * as `glass_surfaces`; see theme.c for why it is not derived here.
     */
    property bool glassSurfaces: false

    // What the desktop widgets actually do. The one property WidgetFrame reads.
    readonly property bool widgetsGlass:
        BarConfig.widgetGlass === "on"  ? true :
        BarConfig.widgetGlass === "off" ? false : root.squareChromeGlass

    /*
     * …and how transparent they are when they do. The ASK was that the widgets
     * match the dock, so this is the dock's own opacity — verbatim.
     *
     * ⚠ IT USED TO BE `dockOpacity + 0.16`, AND THE REASON THAT LIFT EXISTED IS
     * NO LONGER TRUE. It was written when quickshell's layer surfaces got no
     * backdrop blur — "a compositor node the dock has and these do not" — so the
     * same alpha over an unblurred photograph really was a sysmon readout nobody
     * could read. Since -379 the card claims `WlrLayershell.namespace =
     * "synui-glass"` and layer.c puts the dock's own blur node behind it
     * (WidgetFrame.qml says so at the top). The lift outlived its reason and
     * became what it looks like: a constant that stopped the widgets ever
     * matching the thing they are defined as matching, and stopped them reaching
     * clear at all — with the dock at 0.00 the widgets still drew at 0.16.
     *
     * Legibility is measured now rather than bought with a constant: see
     * `legibility` and popupAlphaOn(), which asks the wallpaper under THIS card
     * whether its text still reads and raises only that card only as far as it
     * has to.
     */
    readonly property real widgetAlpha: BarConfig.dockOpacity

    property FileView chromeFile: FileView {
        path: Quickshell.env("HOME") + "/.config/synui/theme.state"
        watchChanges: true
        // Synchronous for the same reason BarConfig's uifxFile is: squareChrome
        // is the other half of "are the corners on", so it too decides whether a
        // floating pill reserves its gap, and the exclusive zone cannot learn
        // that a frame later. A retro desktop read asynchronously would come up
        // holding a gap it does not draw.
        blockLoading: true
        printErrors: false      // absent until a theme is picked
        onFileChanged: reload()
        onLoaded: {
            const t = this.text()
            const m = t.match(/^\s*square_chrome\s*=\s*(\S+)\s*$/m)
            root.squareChrome = !!m && m[1] === "on"
            // Absent means a synui too old to export it, which is a desktop
            // whose widgets have always been the HUD panel. Off is the honest
            // answer for both that and a theme that really is not glass.
            const g = t.match(/^\s*glass_chrome\s*=\s*(\S+)\s*$/m)
            root.squareChromeGlass = !!g && g[1] === "on"
            // Whether glass is actually being DRAWN — the preset having asked
            // for it, transparency on, and blur on. Not derivable from the line
            // above: see theme.c, which exports it for exactly that reason.
            // Absent is a synui too old to say, and "off" is the desktop those
            // machines already have.
            const gs = t.match(/^\s*glass_surfaces\s*=\s*(\S+)\s*$/m)
            root.glassSurfaces = !!gs && gs[1] === "on"
        }
        onLoadFailed: {
            root.squareChrome = false
            root.squareChromeGlass = false
            root.glassSurfaces = false
        }
    }

    // Module pills are inset from the bar's height so the hover wash reads as a
    // button rather than a full-height stripe. 20 of 28 leaves 4px above and
    // below; the radius is half the height, which is what makes it a pill and
    // not a rounded box.
    readonly property int  pillHeight:    20
    readonly property int  pillRadius:    10

    // Auto-hide: the strip left taking pointer input while the bar is hidden,
    // and how long it waits before dropping once nothing wants it up. The strip
    // has to be thicker than a hairline on a monitor whose top edge is not the
    // layout's top edge — there the pointer arrives from the screen above at
    // whatever step the motion event carries instead of being clamped to y=0,
    // so a 1-2px target gets jumped clean over. The delay is what stops a
    // pointer merely crossing the edge from flapping the bar down and back up.
    readonly property int  barEdgeStrip:  5
    readonly property int  barHideDelay:  260

    // Follows the picker; DejaVu Sans Mono is the floor, and what a box that
    // has never picked one keeps looking like.
    readonly property string fontFamily:  root.uiFont !== "" ? root.uiFont
                                                             : "DejaVu Sans Mono"
    // NOT the picked font, ever. These are the Nerd Font's Private-Use
    // codepoints, and no ordinary family has a glyph at U+F026 — pointing this
    // at "Adwaita Sans" turns every module's icon into a tofu box and collapses
    // the icon-only modules (bluetooth) to zero width.
    readonly property string iconFamily:  "Symbols Nerd Font Mono"
    readonly property int    fontSize:    12
    readonly property int    iconSize:    13

    // Shared easing so every module animates identically.
    readonly property int  animFast:   120
    readonly property int  animNormal: 180
}
