/*
 * geom_persist.c — remember each app's window geometry across restarts
 *
 * When a window unmaps, its outer frame geometry and maximized state are
 * recorded against its app_id in ~/.config/synui/windows.conf. The next
 * window that app opens is placed there instead of getting the centred
 * default from layout_float_place().
 *
 * Keyed by app_id, not per-window: the point is "Firefox opens at the size I
 * last left Firefox", so several windows of one app share an entry and the
 * last one to close wins. That is what every desktop that does this does.
 *
 * Only *free* windows are recorded. A tiled window's geometry belongs to the
 * layout engine, and a fullscreen one's belongs to the output, so saving
 * either would hand back a size the user never chose. Maximized windows are
 * recorded as maximized, with the restore geometry underneath, so the app
 * comes back maximized and un-maximizes to the right box.
 *
 * SynapseOS Project
 * SPDX-License-Identifier: GPL-2.0-or-later
 * https://github.com/velle999/SYNAPSE
 */

#define _GNU_SOURCE
#include <ctype.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

#include "synui.h"

#define GEOM_PERSIST_MAX 64

typedef struct {
    char app_id[128];
    int  x, y, w, h;
    int  maximized;
} geom_entry_t;

static geom_entry_t table[GEOM_PERSIST_MAX];
static int table_count  = 0;
static int table_loaded = 0;

static void windows_path(char *buf, size_t len)
{
    buf[0] = '\0';
    const char *env = getenv("SYNUI_WINDOWS");
    if (env && env[0]) { snprintf(buf, len, "%s", env); return; }

    syn_config_path(buf, len, "windows.conf");
}

/*
 * app_id is the first field on the line and the fields are space-separated,
 * so an app_id containing whitespace (X11 WM_CLASS is allowed to) would make
 * the line unparseable. Fold whitespace to '_' on both save and lookup so the
 * two always agree; the theoretical collision between "a b" and "a_b" is
 * worth a format that stays greppable by hand.
 */
static void key_of(const char *app_id, char *buf, size_t len)
{
    snprintf(buf, len, "%s", app_id ? app_id : "");
    for (char *p = buf; *p; p++)
        if (isspace((unsigned char)*p)) *p = '_';
}

static geom_entry_t *table_find(const char *key)
{
    for (int i = 0; i < table_count; i++)
        if (!strcmp(table[i].app_id, key))
            return &table[i];
    return NULL;
}

static void table_load(void)
{
    if (table_loaded) return;
    table_loaded = 1;

    char path[256];
    windows_path(path, sizeof(path));
    if (!path[0]) return;

    FILE *f = fopen(path, "r");
    if (!f) return;

    char line[512];
    while (table_count < GEOM_PERSIST_MAX && fgets(line, sizeof(line), f)) {
        char *s = line;
        while (isspace((unsigned char)*s)) s++;
        if (strncmp(s, "window ", 7) != 0) continue;
        s += 7;

        char *tok = strtok(s, " \t\r\n");
        if (!tok) continue;

        geom_entry_t *e = &table[table_count];
        memset(e, 0, sizeof(*e));
        snprintf(e->app_id, sizeof(e->app_id), "%s", tok);

        while ((tok = strtok(NULL, " \t\r\n"))) {
            char *eq = strchr(tok, '=');
            if (!eq) continue;
            *eq = '\0';
            const char *val = eq + 1;
            if      (!strcmp(tok, "x"))         e->x         = atoi(val);
            else if (!strcmp(tok, "y"))         e->y         = atoi(val);
            else if (!strcmp(tok, "w"))         e->w         = atoi(val);
            else if (!strcmp(tok, "h"))         e->h         = atoi(val);
            else if (!strcmp(tok, "maximized")) e->maximized = atoi(val);
        }

        /* Drop entries below the placement floor rather than clamping them up:
         * a file written before the save-side guards existed still holds
         * tooltip- and splash-sized boxes, and silently dropping one means the
         * app gets its normal default placement back instead of a 2x1 window
         * inflated to 40x40. */
        if (e->w >= MIN_WIN && e->h >= MIN_WIN)
            table_count++;
    }
    fclose(f);
}

static void ensure_parent_dir(const char *path)
{
    char dir[256];
    snprintf(dir, sizeof(dir), "%s", path);
    char *slash = strrchr(dir, '/');
    if (!slash) return;
    *slash = '\0';
    if (mkdir(dir, 0755) != 0 && errno != EEXIST)
        wlr_log(WLR_ERROR, "synui: mkdir %s failed: %s", dir, strerror(errno));
}

static void table_write(void)
{
    char path[256];
    windows_path(path, sizeof(path));
    if (!path[0]) return;

    ensure_parent_dir(path);
    FILE *f = fopen(path, "w");
    if (!f) {
        wlr_log(WLR_ERROR, "synui: can't save window geometry to %s: %s",
                path, strerror(errno));
        return;
    }

    fprintf(f, "# synui per-app window geometry — autogenerated when a window\n"
               "# closes. Each app's last free (non-tiled, non-fullscreen)\n"
               "# geometry, reused the next time that app opens a window.\n"
               "# Delete a line to forget one app; delete the file to forget\n"
               "# all of them. Set remember_geometry = 0 in synuirc to stop\n"
               "# recording entirely.\n");
    for (int i = 0; i < table_count; i++) {
        geom_entry_t *e = &table[i];
        fprintf(f, "window %s x=%d y=%d w=%d h=%d maximized=%d\n",
                e->app_id, e->x, e->y, e->w, e->h, e->maximized);
    }
    fclose(f);
}

/*
 * Record this view's geometry, if it is the sort of geometry the user chose.
 * Called from the unmap handlers. A maximized window stores the geometry it
 * would restore to, so reopening it maximized still un-maximizes correctly.
 */
void geom_persist_save(syn_view_t *view)
{
    if (!view || !view->server->config.remember_geometry) return;
    if (view->fullscreen || view->minimized) return;

    /* Only a real toplevel on a desktop is "a window this app opened".
     *
     * X11 override-redirect surfaces — menus, tooltips, drag icons — reach
     * this function too: xw_unmap is hooked for every surface, and an OR view
     * never joins a workspace, so the tiled-geometry test below used to fall
     * through on the NULL workspace and record them. They carry the app's
     * WM_CLASS, so a Steam tooltip closing wrote `steam w=2 h=1` over the real
     * entry and Steam then reopened 2x1. */
    if (view->override_redirect || !view->workspace) return;

    /* Same clobber, one level up: a dialog shares its parent's app_id, so
     * saving it would hand the app's next *main* window the size of its last
     * file picker. Only parentless toplevels get a say. */
    if (view->is_xwayland) {
        if (view->xsurface->parent || view->xsurface->modal) return;
    } else if (view->xdg_surface->toplevel->parent) {
        return;
    }

    /* Tiled geometry is the layout engine's, not the user's. */
    if (!view->floating && !view->maximized &&
        view->workspace->layout != LAYOUT_FLOATING)
        return;

    const char *app = view_app_id(view);
    if (!app || !app[0]) return;

    char key[128];
    key_of(app, key, sizeof(key));

    int x = view->x, y = view->y, w = view->w, h = view->h;
    if (view->maximized) {
        /* view->x/y/w/h is the output box while maximized; the box the user
         * actually sized is the saved restore geometry. */
        x = view->saved_geo.x;
        y = view->saved_geo.y;
        w = view->saved_geo.width;
        h = view->saved_geo.height;
    }
    /* Below the placement floor there is nothing worth remembering: layout.c
     * would only clamp it back up to MIN_WIN, and a splash screen that closed
     * at 134x47 would have overwritten the real window's entry to say so. */
    if (w < MIN_WIN || h < MIN_WIN) return;

    table_load();
    geom_entry_t *e = table_find(key);
    if (!e) {
        if (table_count >= GEOM_PERSIST_MAX) {
            /* Evict the oldest entry; this is a convenience cache, not a
             * ledger, and an unbounded file would be worse. */
            memmove(&table[0], &table[1], sizeof(table[0]) * (GEOM_PERSIST_MAX - 1));
            table_count = GEOM_PERSIST_MAX - 1;
        }
        e = &table[table_count++];
        memset(e, 0, sizeof(*e));
        snprintf(e->app_id, sizeof(e->app_id), "%s", key);
    }

    e->x = x; e->y = y; e->w = w; e->h = h;
    e->maximized = view->maximized ? 1 : 0;

    table_write();
}

/*
 * Look up this app's remembered geometry. Returns false if nothing is saved,
 * in which case the caller's own default placement stands.
 *
 * The caller does the clamping: layout.c already owns the usable-area helper
 * and the minimum-size rule, and it is the one that has to guarantee the
 * result lands on a monitor that currently exists — an entry written on a
 * three-monitor desk must not open the window off the edge of a laptop.
 */
bool geom_persist_lookup(syn_view_t *view, struct wlr_box *box, int *maximized)
{
    if (!view || !view->server->config.remember_geometry) return false;
    if (view->fullscreen) return false;

    const char *app = view_app_id(view);
    if (!app || !app[0]) return false;

    char key[128];
    key_of(app, key, sizeof(key));

    table_load();
    geom_entry_t *e = table_find(key);
    if (!e) return false;

    *box = (struct wlr_box){ e->x, e->y, e->w, e->h };
    *maximized = e->maximized;
    return true;
}
