#!/usr/bin/env python3
"""
i18n-gen.py — build lang/<code>.sh from a list of translations.

    tools/i18n-gen.py de < de.txt

`de.txt` is one translation per line, in exactly the order
`i18n-extract.py --list` prints, with `\n` for an embedded newline and an EMPTY
line for "not translated yet" (which prints the English, so an unfinished file
is a working file).

⚠ THE PAIRING IS POSITIONAL, AND THAT IS ONLY SAFE BECAUSE IT IS CHECKED. A
line count that does not match the key count is refused outright rather than
silently shifting every translation onto the wrong sentence — which, in a
script that partitions disks, would put somebody else's words next to "ALL DATA
WILL BE ERASED". The generated file itself is keyed by the English, so once it
is written the pairing cannot drift again; this is a build step, not the format.

`--verify` prints each pair for reading, which is the other half of not
trusting a count.

SynapseOS Project
SPDX-License-Identifier: GPL-2.0-or-later
"""
import sys
import pathlib

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from importlib import import_module           # noqa: E402
extract = import_module("i18n-extract".replace("-", "_")) if False else None

import re                                     # noqa: E402


def load_keys(root: pathlib.Path):
    src = (root / "syn-install.sh").read_text(encoding="utf-8")
    spec = root / "tools" / "i18n-extract.py"
    ns = {"__name__": "extract", "__file__": str(spec)}
    exec(compile(spec.read_text(encoding="utf-8"), str(spec), "exec"), ns)
    return ns["strings"](src)


def bash_quote(s: str) -> str:
    return (s.replace("\\", "\\\\").replace('"', '\\"')
             .replace("$", "\\$").replace("`", "\\`"))


NAMES = {
    "de": "Deutsch", "fr": "Français", "es": "Español", "pt": "Português",
    "it": "Italiano", "nl": "Nederlands", "pl": "Polski", "ru": "Русский",
    "ja": "日本語", "zh": "中文", "ko": "한국어", "hi": "हिन्दी", "ar": "العربية",
}


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 2
    code = sys.argv[1]
    root = pathlib.Path(__file__).resolve().parent.parent
    keys = load_keys(root)

    body = sys.stdin.read().split("\n")
    while body and body[-1] == "":
        body.pop()

    if len(body) != len(keys):
        print("REFUSED: %d translations for %d strings — the pairing is "
              "positional, so a mismatch would shift every line onto the wrong "
              "sentence." % (len(body), len(keys)), file=sys.stderr)
        return 1

    if "--verify" in sys.argv:
        for k, v in zip(keys, body):
            if v.strip():
                print("EN: %s\n%s: %s\n" % (k.replace("\n", "\\n"), code, v))
        return 0

    out = [
        "# %s (%s) — syn-install's own words." % (NAMES.get(code, code), code),
        "#",
        "# ⚠ GENERATED by tools/i18n-gen.py, but EDITABLE BY HAND — the keys are",
        "# the English sentences, so a correction here needs no tooling and no",
        "# regeneration. Adding a key that matches no English string is the one",
        "# mistake that matters, and tests/i18n_test.sh fails on it.",
        "#",
        "# An entry left empty prints the English. That is not a failure state:",
        "# an installer that says one screen in English is usable, and one that",
        "# says a screen wrong is not.",
        "#",
        "# SPDX-License-Identifier: GPL-2.0-or-later",
        "declare -gA SYN_T=(",
    ]
    n = 0
    for k, v in zip(keys, body):
        if not v.strip():
            continue
        v = v.replace("\\n", "\n")
        out.append('  ["%s"]="%s"' % (bash_quote(k), bash_quote(v)))
        n += 1
    out.append(")")

    dest = root / ("lang-%s.sh" % code)
    
    dest.write_text("\n".join(out) + "\n", encoding="utf-8")
    print("%s: %d/%d strings" % (dest, n, len(keys)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
