#!/bin/sh
# synui-widgets — turn the desktop widgets on and off.
#
# The single writer of ~/.config/synui/widgets.state. The bar watches that file
# (quickshell WidgetState.qml, FileView watchChanges), so a change here repaints
# the desktop immediately — there is no reload to trigger and no IPC involved.
#
# synui's Super+Shift+A bind and the control panel's Widgets row both run this
# command rather than writing the file themselves, so however the toggle is
# reached there is exactly one format and one place it can be wrong.
#
# Everything is OFF by default and the file does not exist until something is
# switched on: these are decoration, and an upgrade must not redecorate the
# desktop of someone who never asked.
#
# SynapseOS Project
# SPDX-License-Identifier: GPL-2.0-or-later
# https://github.com/velle999/SYNAPSE
set -u

CONF_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
STATE="$CONF_HOME/synui/widgets.state"
# Where a dragged widget's corner is remembered. NOT written here — see `home`.
POS="$CONF_HOME/synui/widgets.pos"

WIDGETS="visualizer sysmon clock launcher postit"

usage() {
    cat <<EOF
usage: synui-widgets [<widget>|all] [on|off|toggle]
       synui-widgets home

  widgets: $WIDGETS

  synui-widgets                     show the current state
  synui-widgets sysmon on           turn one on
  synui-widgets visualizer toggle   flip one
  synui-widgets postit on           a note on the desktop, click it to write
  synui-widgets all off             turn everything off
  synui-widgets toggle              flip everything as a group:
                                    all off if any is on, else all on
  synui-widgets home                put every widget back in its designed
                                    corner, undoing every drag

Widgets are dragged by the grip in their top-right corner — on the reporting
ones that grip is the only part that takes a click at all, so everything else
still goes through to the desktop. Double-clicking a grip sends that one widget
home; the command above sends all of them.

The visualiser needs cava (an optdepend); without it that widget stays dark
however this file is set.
EOF
}

# Read one widget's state. Absent file or absent key both mean off.
get() {
    [ -f "$STATE" ] || { echo off; return; }
    val=$(sed -n "s/^[[:space:]]*$1[[:space:]]*=[[:space:]]*\([a-z]*\).*/\1/p" "$STATE" | tail -1)
    [ "$val" = on ] && echo on || echo off
}

# Rewrite the whole file from the current values. Written to a temp file
# and renamed: the bar is watching this path, and a rename is atomic, so it can
# never read a half-written file and redraw from it.
put() {
    mkdir -p "$(dirname "$STATE")" 2>/dev/null
    tmp="$STATE.tmp.$$"
    {
        echo "# Generated by synui-widgets — desktop widget toggles."
        echo "# Watched live by the bar; edit with synui-widgets, not by hand."
        for w in $WIDGETS; do
            eval "printf '%s = %s\n' \"\$w\" \"\$new_$w\""
        done
    } > "$tmp" 2>/dev/null || { rm -f "$tmp"; echo "synui-widgets: cannot write $STATE" >&2; exit 1; }
    mv -f "$tmp" "$STATE" || { rm -f "$tmp"; exit 1; }
}

load() { for w in $WIDGETS; do eval "new_$w=\$(get $w)"; done; }

valid() {
    for w in $WIDGETS; do [ "$1" = "$w" ] && return 0; done
    return 1
}

flip() { [ "$1" = on ] && echo off || echo on; }

case "${1:-}" in
    -h|--help|help) usage; exit 0 ;;
    home)
        # The ONE thing this script does to widgets.pos, and it is a removal.
        #
        # That file is written by the bar (quickshell WidgetLayout.qml), which
        # is the only thing that knows where a pointer let go of a widget — the
        # exact opposite of widgets.state, whose single writer is this script.
        # Parsing and rewriting its JSON here would put a second author on a
        # format neither of us owns. Deleting it is not that: it restores the
        # documented default, which is what an absent file already means.
        rm -f "$POS" || exit 1
        echo "  positions  home"
        exit 0
        ;;
esac

load

# No arguments: report.
if [ $# -eq 0 ]; then
    for w in $WIDGETS; do eval "printf '  %-11s %s\n' \"\$w\" \"\$new_$w\""; done
    exit 0
fi

target="$1"
action="${2:-toggle}"

case "$action" in
    on|off|toggle) ;;
    *) echo "synui-widgets: unknown action '$action'" >&2; usage >&2; exit 2 ;;
esac

if [ "$target" = all ] || [ "$target" = toggle ]; then
    # `synui-widgets toggle` with no widget is the keybind's case: one key that
    # clears the desktop and puts it back. Group-toggle turns everything OFF if
    # anything is on, so the bind always has a predictable "hide it all".
    if [ "$target" = toggle ]; then
        anyon=off
        for w in $WIDGETS; do
            eval "cur=\$new_$w"
            [ "$cur" = on ] && anyon=on
        done
        [ "$anyon" = on ] && action=off || action=on
    fi
    for w in $WIDGETS; do eval "new_$w=\$action"; done
    put
    for w in $WIDGETS; do eval "printf '  %-11s %s\n' \"\$w\" \"\$new_$w\""; done
    exit 0
fi

if ! valid "$target"; then
    echo "synui-widgets: unknown widget '$target'" >&2
    usage >&2
    exit 2
fi

eval "cur=\$new_$target"
[ "$action" = toggle ] && action=$(flip "$cur")
eval "new_$target=\$action"
put
printf '  %-11s %s\n' "$target" "$action"
