/* appstream.c — Flathub's category index.
 *
 * `flatpak search` is the only discovery the flatpak CLI offers, and it takes
 * a search TERM: there is no "show me the games". The categories are not
 * missing, they are simply not on the command line — every remote ships an
 * AppStream catalogue, and flatpak has already downloaded and decompressed
 * Flathub's under /var/lib/flatpak/appstream. Reading that file is what lets
 * the GUI's Flathub tab be browsed by category the way the Arsenal tab is
 * browsed by group, and it costs no network and no extra process.
 *
 * This is a SCANNER, not an XML parser, and that is a deliberate limit rather
 * than a shortcut: linking libxml2 to read five fixed fields would make a
 * package manager depend on an XML stack, and the catalogue is generated by
 * appstream-builder, so the shapes it emits are narrow and stable. The rule
 * the scanner follows is that it never guesses — a component whose fields it
 * cannot read cleanly is skipped entirely rather than emitted half-parsed,
 * because a row with the wrong id is a row that installs the wrong thing.
 *
 * SynapseOS Project — GPL-2.0-or-later
 * SPDX-License-Identifier: GPL-2.0-or-later
 */
#define _GNU_SOURCE
#include "synpkg.h"

#include <dirent.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

/* ── locating the catalogue ─────────────────────────────────────────────── */

/* flatpak keeps a per-installation, per-remote, per-arch tree and points
 * `active` at the current commit. The arch directory is discovered rather than
 * assumed: flatpak's arch names are its own (x86_64, aarch64), and a hardcoded
 * one would silently produce "Flathub has no categories" on any other machine
 * instead of an error anybody could act on. */
static char *find_under(const char *root)
{
	char *base = xasprintf("%s/appstream/%s", root, SYNPKG_FLATHUB_NAME);
	DIR *d = opendir(base);
	if (!d) {
		free(base);
		return NULL;
	}

	char *found = NULL;
	struct dirent *e;
	while (!found && (e = readdir(d))) {
		if (e->d_name[0] == '.')
			continue;
		/* Plain .xml first: flatpak writes both, and the compressed copy is
		 * the fallback rather than the normal case. */
		static const char *tails[] = { "active/appstream.xml",
		                               "active/appstream.xml.gz" };
		for (size_t i = 0; i < sizeof tails / sizeof *tails && !found; i++) {
			char *p = xasprintf("%s/%s/%s", base, e->d_name, tails[i]);
			if (access(p, R_OK) == 0)
				found = p;
			else
				free(p);
		}
	}

	closedir(d);
	free(base);
	return found;
}

static char *slurp(const char *path)
{
	FILE *f = fopen(path, "r");
	if (!f)
		return NULL;

	size_t cap = 1 << 20, len = 0;
	char *text = xmalloc(cap);
	for (;;) {
		if (len + 1 >= cap) {
			cap *= 2;
			text = xrealloc(text, cap);
		}
		size_t n = fread(text + len, 1, cap - len - 1, f);
		if (n == 0)
			break;
		len += n;
	}
	text[len] = '\0';
	fclose(f);
	return text;
}

/* The whole catalogue as one NUL-terminated buffer, or NULL if this machine
 * has no Flathub appstream index — which is a real and common state, not an
 * error: a freshly added remote has none until `flatpak update --appstream`
 * runs. Callers must distinguish it from "no results". */
static char *index_path(void)
{
	char *path = NULL;

	/* An explicit override does NOT fall back to the discovered index. A
	 * test that pointed at a fixture and silently got the machine's real
	 * 48MB catalogue instead would pass for the wrong reason, and one that
	 * asked for "no index at all" could not be written. Same rule as
	 * SYNPKG_CURATED. */
	const char *env = getenv("SYNPKG_APPSTREAM");
	if (env && *env) {
		if (access(env, R_OK) != 0)
			return NULL;
		path = xstrdup(env);
	}

	if (!path) {
		char *user = NULL;
		const char *home = getenv("HOME");
		if (home && *home)
			user = xasprintf("%s/.local/share/flatpak", home);

		/* User installation first: if an app exists in both, the user's copy
		 * is the one `flatpak install` will act on without --system. */
		path = user ? find_under(user) : NULL;
		if (!path)
			path = find_under("/var/lib/flatpak");
		free(user);
	}

	return path;
}

/* Whether this machine has an index at all, WITHOUT reading 48MB to find out.
 * The About pane asks once per open and only wants the yes/no. */
bool sp_appstream_present(void)
{
	char *path = index_path();
	bool have = path != NULL;
	free(path);
	return have;
}

static char *read_index(void)
{
	char *path = index_path();
	if (!path)
		return NULL;

	size_t len = strlen(path);
	char *text;
	if (len > 3 && !strcmp(path + len - 3, ".gz")) {
		/* zlib as a hard dependency to decompress one optional fallback file
		 * is a poor trade; gzip is in base and this path is rare. */
		char *argv[] = { (char *)"gzip", (char *)"-dc", path, NULL };
		int st = 0;
		text = run_capture(argv, &st, true);
		if (st != 0) {
			free(text);
			text = NULL;
		}
	} else {
		text = slurp(path);
	}

	free(path);
	return text;
}

/* ── scanning ───────────────────────────────────────────────────────────── */

static const char *find_in(const char *p, const char *end, const char *needle)
{
	if (!p || p >= end)
		return NULL;
	return memmem(p, (size_t)(end - p), needle, strlen(needle));
}

static char *dupn(const char *s, size_t n)
{
	char *out = xmalloc(n + 1);
	memcpy(out, s, n);
	out[n] = '\0';
	return out;
}

/* The five predefined XML entities, decoded in place. Anything else — a
 * numeric character reference, say — is passed through VERBATIM rather than
 * guessed at: appstream-builder writes UTF-8 directly, so numeric references
 * are vanishingly rare here, and a mangled description is worse than a literal
 * one. */
static void unescape(char *s)
{
	static const struct { const char *ent; char ch; } ents[] = {
		{ "&amp;", '&' }, { "&lt;", '<' }, { "&gt;", '>' },
		{ "&quot;", '"' }, { "&apos;", '\'' },
	};

	char *w = s;
	for (const char *r = s; *r; ) {
		if (*r != '&') {
			*w++ = *r++;
			continue;
		}
		bool hit = false;
		for (size_t i = 0; i < sizeof ents / sizeof *ents && !hit; i++) {
			size_t n = strlen(ents[i].ent);
			if (!strncmp(r, ents[i].ent, n)) {
				*w++ = ents[i].ch;
				r += n;
				hit = true;
			}
		}
		if (!hit)
			*w++ = *r++;
	}
	*w = '\0';
}

/* Text of the first UNQUALIFIED <tag> in [p, end).
 *
 * "Unqualified" is the whole point: AppStream repeats every human-readable
 * field once per translation as <summary xml:lang="pl">, and matching "<summary"
 * would hand back whichever language happened to come first. Matching the exact
 * bytes "<summary>" selects the untranslated original every time. */
static char *tag_text(const char *p, const char *end, const char *tag)
{
	char *open = xasprintf("<%s>", tag);
	char *close = xasprintf("</%s>", tag);

	char *out = NULL;
	const char *a = find_in(p, end, open);
	if (a) {
		a += strlen(open);
		const char *b = find_in(a, end, close);
		if (b) {
			out = dupn(a, (size_t)(b - a));
			unescape(out);
		}
	}

	free(open);
	free(close);
	return out;
}

/* The flatpak ref id, taken from <bundle>app/<id>/<arch>/<branch></bundle>.
 *
 * NOT from <id>: 474 of Flathub's components carry a legacy <id> with a
 * trailing ".desktop", and `flatpak install org.gnome.Boxes.desktop` is not a
 * thing. The bundle ref is what flatpak itself resolves, so it is the only
 * field whose value is guaranteed to be installable. */
static char *bundle_id(const char *p, const char *end)
{
	const char *b = find_in(p, end, "<bundle");
	if (!b)
		return NULL;
	const char *gt = memchr(b, '>', (size_t)(end - b));
	if (!gt)
		return NULL;
	const char *close = find_in(gt, end, "</bundle>");
	if (!close)
		return NULL;

	const char *s = gt + 1;
	if ((size_t)(close - s) < 4 || strncmp(s, "app/", 4))
		return NULL;   /* a runtime or an extension, not an application */
	s += 4;

	const char *slash = memchr(s, '/', (size_t)(close - s));
	if (!slash || slash == s)
		return NULL;
	return dupn(s, (size_t)(slash - s));
}

/* Newest <release version="..."/>. AppStream lists releases newest-first, so
 * the first one is the current version. Absent for plenty of apps, which is
 * why callers must treat "" as "unknown" and not as a fault. */
static char *release_version(const char *p, const char *end)
{
	const char *rs = find_in(p, end, "<releases>");
	if (!rs)
		return NULL;
	const char *re = find_in(rs, end, "</releases>");
	if (!re)
		re = end;

	const char *v = find_in(rs, re, " version=\"");
	if (!v)
		return NULL;
	v += strlen(" version=\"");
	const char *q = memchr(v, '"', (size_t)(re - v));
	if (!q)
		return NULL;

	char *out = dupn(v, (size_t)(q - v));
	unescape(out);
	return out;
}

/* Every <category> as "\nGame\nActionGame\n", so membership is a whole-line
 * match. A bare substring test would put every ArcadeGame in Game — which is
 * true here by luck, and false for Audio inside AudioVideo. */
static char *categories_of(const char *p, const char *end)
{
	const char *cs = find_in(p, end, "<categories>");
	if (!cs)
		return NULL;
	const char *ce = find_in(cs, end, "</categories>");
	if (!ce)
		return NULL;

	size_t cap = 64, len = 1;
	char *out = xmalloc(cap);
	out[0] = '\n';
	out[1] = '\0';

	for (const char *q = cs; (q = find_in(q, ce, "<category>")); ) {
		q += strlen("<category>");
		const char *e = find_in(q, ce, "</category>");
		if (!e)
			break;
		size_t n = (size_t)(e - q);
		while (len + n + 2 >= cap) {
			cap *= 2;
			out = xrealloc(out, cap);
		}
		memcpy(out + len, q, n);
		len += n;
		out[len++] = '\n';
		out[len] = '\0';
		q = e;
	}

	if (len == 1) {   /* <categories/> with nothing in it */
		free(out);
		return NULL;
	}
	return out;
}

/* Component types that are APPLICATIONS. Runtimes, addons, localisation packs
 * and generic components all appear in the same catalogue and none of them is
 * something to offer somebody browsing for software. */
static bool is_application(const char *p, const char *end)
{
	const char *t = find_in(p, end, "type=\"");
	if (!t)
		return false;
	t += strlen("type=\"");
	const char *q = memchr(t, '"', (size_t)(end - t));
	if (!q)
		return false;

	size_t n = (size_t)(q - t);
	static const char *ok[] = { "desktop-application", "desktop",
	                            "console-application" };
	for (size_t i = 0; i < sizeof ok / sizeof *ok; i++)
		if (n == strlen(ok[i]) && !strncmp(t, ok[i], n))
			return true;
	return false;
}

static int by_name(const void *a, const void *b)
{
	const sp_as_app *x = a, *y = b;
	const char *xs = *x->name ? x->name : x->id;
	const char *ys = *y->name ? y->name : y->id;
	int c = strcasecmp(xs, ys);
	return c ? c : strcmp(x->id, y->id);
}

sp_as_app *sp_appstream_load(size_t *count)
{
	*count = 0;

	char *text = read_index();
	if (!text)
		return NULL;

	size_t cap = 4096, n = 0;
	sp_as_app *apps = xmalloc(cap * sizeof *apps);

	for (char *p = text; (p = strstr(p, "<component")); ) {
		/* "<component" is a PREFIX of "<components", the document's own root
		 * element. Without this check the very first match is the root tag,
		 * its "end" is the first real component's closing tag, and the scan
		 * resumes past it — silently dropping exactly one application, always
		 * the first one, with no error anywhere. */
		char after = p[strlen("<component")];
		if (after != ' ' && after != '>' && after != '\t'
		    && after != '\n' && after != '/') {
			p += strlen("<component");
			continue;
		}

		char *end = strstr(p, "</component>");
		if (!end)
			break;

		/* The opening tag only, for the type attribute — searching the whole
		 * component would find a type= on some nested element. */
		char *gt = memchr(p, '>', (size_t)(end - p));
		if (gt && is_application(p, gt)) {
			char *id = bundle_id(p, end);
			char *cats = id ? categories_of(p, end) : NULL;

			/* No categories means nothing to file it under. Dropping it here
			 * rather than in the caller is what keeps the runtime/theme noise
			 * out of every count. */
			if (id && cats) {
				char *name = tag_text(p, end, "name");
				char *summary = tag_text(p, end, "summary");
				char *version = release_version(p, end);

				if (n == cap) {
					cap *= 2;
					apps = xrealloc(apps, cap * sizeof *apps);
				}
				apps[n++] = (sp_as_app){
					.id = id,
					.name = name ? name : xstrdup(""),
					.summary = summary ? summary : xstrdup(""),
					.version = version ? version : xstrdup(""),
					.cats = cats,
				};
			} else {
				free(id);
				free(cats);
			}
		}

		p = end + strlen("</component>");
	}

	free(text);

	/* Catalogue order is by application id, so an unsorted pane reads as
	 * "ai.jan.Jan, ai.lmstudio…" — sorted by the name actually displayed. */
	qsort(apps, n, sizeof *apps, by_name);

	*count = n;
	return apps;
}

void sp_appstream_free(sp_as_app *apps, size_t n)
{
	for (size_t i = 0; i < n; i++) {
		free(apps[i].id);
		free(apps[i].name);
		free(apps[i].summary);
		free(apps[i].version);
		free(apps[i].cats);
	}
	free(apps);
}

bool sp_appstream_in(const sp_as_app *a, const char *category)
{
	char *wrapped = xasprintf("\n%s\n", category);
	bool hit = strstr(a->cats, wrapped) != NULL;
	free(wrapped);
	return hit;
}
