#!/usr/bin/env bash
# iso-repro-diff.sh — two ISOs built from one commit: what differs, and why?
#
# docs/SECURITY-ROADMAP.md §4 asks for two builds of the same commit to differ
# only in ways that are LISTED, and for "is it still reproducible" to be a
# command. This is the command:
#
#   tools/iso-repro-diff.sh A.iso B.iso
#
# Build the same commit twice (sudo archiso/build.sh, keeping the first ISO
# aside), then run this as your normal user. It needs no root: xorriso reads
# the images and unsquashfs unpacks airootfs.sfs (device nodes and set-id bits
# it cannot recreate as a user are compared from the listing instead).
#
# Every differing path is filed under a CAUSE — a pattern below with the reason
# it differs. What matches no cause is printed as UNEXPLAINED, and that list is
# the one to drive to empty: a new line in it is either a new cause to write
# down here or a real non-determinism to fix. The listed causes are not
# excuses by being listed; each says what would remove it.
#
# Exit: 0 identical, 1 differ only by listed causes, 2 anything unexplained,
# 3 usage/tool error. KEEP=1 keeps the unpacked trees.
#
# SynapseOS Project
# SPDX-License-Identifier: GPL-2.0-or-later
set -uo pipefail

[ $# -eq 2 ] && [ -r "$1" ] && [ -r "$2" ] || { sed -n '4,12p' "$0" >&2; exit 3; }
for t in xorriso unsquashfs sha256sum; do
    command -v "$t" >/dev/null || { echo "iso-repro-diff: needs $t" >&2; exit 3; }
done

A=$(realpath "$1") B=$(realpath "$2")
if cmp -s "$A" "$B"; then
    echo "identical: $(sha256sum "$A" | cut -c1-16)…"
    exit 0
fi

work=$(mktemp -d "${TMPDIR:-/tmp}/iso-diff.XXXXXX")
if [ -z "${KEEP:-}" ]; then trap 'rm -rf "$work"' EXIT; else echo "work dir: $work"; fi

# ── The causes ────────────────────────────────────────────────────────────────
# pattern (extended regex on the path, from the image root or the squashfs
# root) <TAB> why it differs, and what would remove it.
causes=$(cat <<'EOF'
^sq/var/lib/pacman/local/[^/]+/desc$	pacman records %INSTALLDATE% — the moment pacstrap ran — for every package. Removable: pacstrap under libfaketime, or rewrite the field to SOURCE_DATE_EPOCH after install.
^sq/var/lib/pacman/sync/	the sync databases are whatever the mirrors served on the day. Removable only by pinning a mirror snapshot (archive.archlinux.org).
^sq/etc/shadow-?$	the password-change day (field 3) is the day the account was created. Removable: set it from SOURCE_DATE_EPOCH in customize_airootfs.
^sq/etc/(passwd|group|gshadow)-$	shadow-utils' backup copies, written when accounts are added.
^sq/etc/machine-id$	systemd identity; should be empty or "uninitialized" on an image — if it differs, a build step generated one.
^sq/var/lib/systemd/	systemd state written during the build (random seed, catalog, timers).
^sq/(etc/ld\.so\.cache|var/cache/ldconfig/aux-cache)$	ldconfig's caches record file mtimes and inode order.
^sq/usr/share/mime/	update-mime-database output.
^sq/(var/cache/fontconfig|usr/lib/fontconfig/cache)/	fontconfig caches embed directory mtimes.
^sq/usr/(lib|share)/.*/(icon-theme\.cache|loaders\.cache|giomodule\.cache|gschemas\.compiled|immodules\.cache)$	GTK/GIO/pixbuf caches generated by install hooks; they embed mtimes or hash order.
\.pyc$	Python bytecode: embeds the source mtime, and compileall order varies. Removable: SOURCE_DATE_EPOCH-aware compile (checked-hash pycs).
^sq/var/log/	logs written during the build.
^sq/(etc/pacman\.d/gnupg|etc/ssh/ssh_host_)	keys generated during the build — must not be identical across images, and must not ship at all if they are host keys.
^sq/usr/lib/modules/[^/]+/modules\.	depmod output; deterministic for identical modules, so a difference here means a module itself differs.
^iso/boot/	the kernel/initramfs as copied to the ISO; the initramfs embeds file mtimes unless mkinitcpio honours SOURCE_DATE_EPOCH.
^iso/EFI/|^iso/(syslinux|limine|boot/grub)/	bootloader images and configs; the FAT/El Torito images carry timestamps.
^iso/arch/	archiso's own metadata (pkglist, version, checksums) — follows from differences above.
EOF
)

classify() {   # path → cause text, or empty
    local p=$1 pat why
    while IFS=$'\t' read -r pat why; do
        [[ -n $pat ]] || continue
        if [[ $p =~ $pat ]]; then printf '%s' "$why"; return; fi
    done <<<"$causes"
}

# ── Unpack ────────────────────────────────────────────────────────────────────
unpack() {   # iso dest
    mkdir -p "$2/iso"
    xorriso -osirrox on -indev "$1" -extract / "$2/iso" >/dev/null 2>&1 \
        || { echo "iso-repro-diff: cannot read $1" >&2; exit 3; }
    chmod -R u+rwX "$2/iso" 2>/dev/null
    local sfs
    sfs=$(find "$2/iso" -name airootfs.sfs | head -1)
    [ -n "$sfs" ] || { echo "iso-repro-diff: no airootfs.sfs in $1" >&2; exit 3; }
    unsquashfs -lln "$sfs" | sed -n 's|^\(.\{10\}\) *\([0-9]*/[0-9]*\) *\([0-9]*\) *\([0-9-]* [0-9:]*\) *squashfs-root\(.*\)$|\5\t\1 \2 \3 \4|p' \
        | sort >"$2/sq.meta"
    unsquashfs -q -n -ig -no -d "$2/sq" "$sfs" >/dev/null 2>&1
    rm -f "$sfs"   # compared through its contents, not as one blob
}
echo "unpacking $(basename "$A")…"; unpack "$A" "$work/a"
echo "unpacking $(basename "$B")…"; unpack "$B" "$work/b"

hashes() {   # dir → "path<TAB>sha" for every regular file and symlink target
    (cd "$1" && find iso sq \( -type f -o -type l \) -print0 2>/dev/null | sort -z |
        while IFS= read -r -d '' f; do
            if [ -L "$f" ]; then printf '%s\tlink:%s\n' "$f" "$(readlink "$f")"
            else printf '%s\t%s\n' "$f" "$(sha256sum <"$f" | cut -c1-64)"; fi
        done)
}
hashes "$work/a" >"$work/a.h"
hashes "$work/b" >"$work/b.h"

# Paths that differ in content, exist on one side only, or differ in metadata
# (mode, owner, size, mtime) as unsquashfs lists them.
{
    join -t $'\t' -a1 -a2 -e MISSING -o 0,1.2,2.2 "$work/a.h" "$work/b.h" \
        | awk -F'\t' '$2 != $3 { print $1 }'
    join -t $'\t' -a1 -a2 -e MISSING -o 0,1.2,2.2 "$work/a/sq.meta" "$work/b/sq.meta" \
        | awk -F'\t' '$2 != $3 { print "sq" $1 }'
} | sort -u >"$work/diffs"

total=$(wc -l <"$work/diffs")
declare -A n ex
unexplained=()
while IFS= read -r p; do
    why=$(classify "$p")
    if [ -z "$why" ]; then unexplained+=("$p"); continue; fi
    n[$why]=$(( ${n[$why]:-0} + 1 ))
    [ -n "${ex[$why]:-}" ] || ex[$why]=$p
done <"$work/diffs"

echo
echo "$total path(s) differ"
for why in "${!n[@]}"; do
    printf '\n  %5d  %s\n         e.g. %s\n' "${n[$why]}" "$why" "${ex[$why]}"
done
if [ ${#unexplained[@]} -gt 0 ]; then
    printf '\n  UNEXPLAINED (%d) — a new cause to list, or a real non-determinism:\n' "${#unexplained[@]}"
    printf '         %s\n' "${unexplained[@]:0:40}"
    [ ${#unexplained[@]} -le 40 ] || echo "         … and $(( ${#unexplained[@]} - 40 )) more"
    exit 2
fi
exit 1
